### ISSUE TITLE
Unicycler failing at "Creating simple long read bridges"

### ISSUE THREAD

**Issue by SophieS9** [rrwick/Unicycler#104]
Hi Unicycler Team,

I'm trying to test and run unicycler on the _K. pneumoniae_ data as analysed [here](https://github.com/rrwick/Bacterial-genome-assemblies-with-multiplex-MinION-sequencing). I downloaded the trimmed illumina reads and subsampled ONT reads from [here](https://figshare.com/projects/Completing_bacterial_genome_assemblies_with_multiplex_MinION_sequencing/23068) just for the barcode01 sample. I'm expecting to get some ONT data in the next few weeks and wanted to test/install Unicycler first.

I've got version 0.4.5 installed and I'm running via the unicycler-runner.py option as follows:
```./unicycler-runner.py -1 illumina_1.fastq.gz -2 illumina_2.fastq.gz -l ONT.fastq.gz -o Unicycler_Out```

I downloaded the latest release from GitHub [here](https://github.com/rrwick/Unicycler/releases) as opposed to using git clone as I've got some separate git issues on my compute cluster.

However I'm getting the following error during the creating simple long read bridges step:
```Traceback (most recent call last):
  File "/nobackup/shared/cgebm/Unicycler-0.4.5/unicycler-runner.py", line 21, in <module>
    main()
  File "/nobackup/shared/cgebm/Unicycler-0.4.5/unicycler/unicycler.py", line 164, in main
    anchor_segments)
  File "/nobackup/shared/cgebm/Unicycler-0.4.5/unicycler/bridge_long_read_simple.py", line 133, in create_simple_long_read_bridges
    anchor_segments)
  File "/nobackup/shared/cgebm/Unicycler-0.4.5/unicycler/bridge_long_read_simple.py", line 355, in simple_bridge_loops
    for loop_count in sorted(votes.keys()):
TypeError: '<' not supported between instances of 'NoneType' and 'int' 
```

I've attached my full log as well.

Would be great to know what's going wrong! 

Thanks!

Sophie 

[unicycler.log](https://github.com/rrwick/Unicycler/files/1974855/unicycler.log)

**Comment by mcroxen** [comment]
hi @SophieS9 - what version of racon do you have installed? from the log it looks like the long read + contig assembly didn't work. I would suggest trying racon 0.5 and not the newest version (1.0+).

**Comment by SophieS9** [comment]
Hi @mcroxen I'm running racon version 1.3.0. I'll try 0.5.0 and get back to you (currently having issues installing 0.5.0 but will let you know when I've got it working and tested!)
