### ISSUE TITLE
Is it possible to make Unicycler use kmer larger than 127 for SPAdes assembly? 

### ISSUE THREAD

**Issue by ilnamkang** [rrwick/Unicycler#108]
Hi,

Is it possible to make Unicycler use kmer larger than 127? 

I've been able to make SPAdes assembler use kmer values larger than 127, by compiling the source code with -DSPADES_MAX_K option. (https://github.com/ablab/spades/issues/40)

If the SPAdes assembler with the increased kmer options is available in $PATH, then can I make Unicycler use kmer larger than 127?

Thanks.

**Comment by rrwick** [comment]
That's very cool - I wasn't aware you could adjust this value!

I've just added some logic to Unicycler (742db3b, in the [development branch](https://github.com/rrwick/Unicycler/tree/development)) which figures out what SPAdes' maximum k-mer size is before making the k-mer choices. It does this by looking at the SPAdes help text, e.g. `must be odd and less than 128` (the default) or `must be odd and less than 256`.

It seems to work nicely on my end, so feel free to give it a try! Assuming there are no issues, this change should make it into the next Unicycler release.

Thanks!
