### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by JCSzamosi** [rrwick/Unicycler#11]
It seems as if the function `_resolve_version()` in ez_setup.py is failing to generate a string required by Python, so all calls to setup.py, including `setup.py -h` are failing. The error is:

`Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    ez_setup.use_setuptools()
  File "/home/jcszamosi/BioinformaticsTools/Unicycler/ez_setup.py", line 150, in use_setuptools
    version = _resolve_version(version)
  File "/home/jcszamosi/BioinformaticsTools/Unicycler/ez_setup.py", line 365, in _resolve_version
    reader = codecs.getreader(charset)
  File "/usr/lib/python3.4/codecs.py", line 994, in getreader
    return lookup(encoding).streamreader
TypeError: must be str, not None`

Thanks!

**Comment by rrwick** [comment]
I believe this one has been fixed (https://github.com/rrwick/Unicycler/commit/8fc7dc34bdad1c8c92b8fe09c0eec39d2616d72e) and now that I've released a new Unicycler version, it's in the master branch. This just updates `ez_setup.py` script to a more recent version, and I think it works now.

I also see that the `ez_setup.py` method of installing setuptools [is deprecated](https://github.com/pypa/setuptools/issues/581). So if this continues to cause trouble in the future, I may just remove it from the Unicycler repo and require people to install setuptools using pip.

Let me know if this fails to fix it!

Ryan
