### ISSUE TITLE
miniasm assembly too small for bridging

### ISSUE THREAD

**Issue by stevenjdunn** [rrwick/Unicycler#122]
Hi,

First off a huge thanks for Unicycler - it's an absolutely amazing piece of work. 

I've been having some issues assembling Klebsiella genomes using ONT + Illumina that result in highly contiguated outputs. While trying to get to the bottom of it I noticed that I get the following line after miniasm assembly:

```
Merging segments into unitigs:
  4 circular unitigs
  total size = 5,715,332 bp
Saving /redacted/for/privacy/miniasm_assembly/12_unitig_graph.gfa

miniasm assembly too small for bridging
```

I think the ultimate reason for the poor completion in this specific sample is the spades assembly (the best spades graph is like a Jackson Pollock). But all of the samples I'm having problems with have this 'too small' line in them.

Can you shed any light on what this line means, and whether it'd likely have any impact on the final assembly?

For reference the ONT data is comprised of 550 megabases with a mean quality of 9.7 and a mean length of 10010 bp.

Thanks!

**Comment by stevenjdunn** [comment]
Been doing some more digging - I’ve figured out why this is happening, but haven’t got my head around all of it. The graph voodoo is largely above my level of understanding!

Looking at the lines 182-190 in miniasm_assembly.py:

            # If the miniasm assembly looks too small, then we don't bother polishing it or using
            # it for bridging.
            if short_reads_available:
                estimated_genome_size = graph.get_estimated_sequence_len()
                target_size = estimated_genome_size * \
                    settings.REQUIRED_MINIASM_ASSEMBLY_SIZE_FOR_BRIDGING
                if unitig_graph_size < target_size:
                    log.log('')
                    log.log(red('miniasm assembly too small for bridging'))
                    unitig_graph = None

With “REQUIRED_MINIASM_ASSEMBLY_SIZE_FOR_BRIDGING” listed as 0.5 under settings.py, line 178, and the estimated graph length coming from assembly_graph.py around line 2160. 

Noted in the estimated sequence length is this:

        Returns an estimate sequence length, based on the depth. E.g. a segment of depth 1.0
        contributes it own length (minus overlaps), a segment of depth 2.5 contributes 2.5 times
        its own length, etc.

Checking the best spades graph shows a total length of 5,611,984 bp and a mean depth of 2.25x. Bingo. Adding a couple of lines to print the target and estimated sizes, and continue to polish regardless of being too small I get:

    target_size = 5931785.181402992
    estimated_genome_size = 11863570.362805985

    target_size/estimated_genome_size = 0.5

But why the large estimated size? Well viewing nodes in the best spades assembly with a depth greater than 10 shows there’s ~28.5 kb of fragmented sequences at a mean depth of 223x, contributing an extra 6.3 Mb to Unicycler’s estimated sequence length, crossing the threshold to set the unitig_graph as none and throwing the ‘too small error’.

I guess the smart solution would be to normalise my fastq depth using something like bbnorm. I’ll do some testing and report back!

So I guess my only question now is why does the graph length check consider depth instead of simple total length?

**Comment by deeptir-unimelb** [comment]
Hi @stevenjdunn 

Did figure out a solution to this?
P.S- I know this was almost 2 years ago but I'm facing the same issue now and unable to get a circularised genome in spite of having good coverage. I am trying to assemble an e.coli genome using illumina and ont reads. It says miniasm assembly too small for bridging and then at the end of the log file, the status is "incomplete"
[unicycler.log](https://github.com/rrwick/Unicycler/files/4407107/unicycler.log)
Thank you for any help/feedback.

**Comment by stevenjdunn** [comment]
I think these are separate issues, and have replied in #233. 

This issue was fixed using bbnorm to normalise the fastq depth. There was a repeat region screwing up the coverage estimation as detailed above.
