### ISSUE TITLE
Different contig names between unicycler.log and assembly.fasta

### ISSUE THREAD

**Issue by semiramisCJ** [rrwick/Unicycler#126]
Dear Ryan,

I have done various hybrid assemblies with Unicycler v0.4.1 with no problems at all. However, in just one case, some contig names reported on the unicycler.log file do not correspond to the same contigs in the assembly.fasta file. It has happened with only a dataset and the results are the same if I re-run the analysis. 
Here is a table with the log file info and the fasta headers. I also double-checked the contig sizes and I confirmed that they are the same as shown in the fasta headers.

I would like to know how if I can avoid those changes on the contig names.

Component | Segments | Links | Length | N50 | Longest segment | Status |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
total | 61 | 63 | 3673244 | 1048285 | 1797259 |   |   | Segment | Length | Depth | Starting gene |  
1 | 51 | 58 | 1809779 | 1797259 | 1797259 | incomplete |   |   |   |   |   | >1 length=1797259 depth=1.00x
2 | 1 | 0 | 1048285 | 1048285 | 1048285 | incomplete |   |   |   |   |   | >2 length=1048285 depth=0.94x
3 | 1 | 0 | 747137 | 747137 | 747137 | incomplete |   |   |   |   |   | >3 length=747137 depth=1.05x
4 | 1 | 0 | 19806 | 19806 | 19806 | incomplete |   |   |   |   |   | >4 length=19806 depth=0.95x
5 | 1 | 1 | 12840 | 12840 | 12840 | complete |   | 5 | 12840 | 1.66x | none found | >5 length=12840 depth=1.66x circular=true
6 | 3 | 3 | 17897 | 11418 | 11418 | incomplete |   |   |   |   |   | >6 length=11418 depth=4.31x
7 | 1 | 0 | 8473 | 8473 | 8473 | incomplete |   |   |   |   |   | >7 length=8473 depth=0.67x
  |   |   |   |   |   |   |   |   |   |   |   | >8 length=6404 depth=1.01x
8 | 1 | 1 | 4723 | 4723 | 4723 | complete |   | 9 | 4723 | 4.63x | none found | >9 length=4723 depth=4.63x circular=true
9 | 1 | 0 | 4304 | 4304 | 4304 | incomplete |   |   |   |   |   | >10 length=4304 depth=1.12x

**Comment by stevenjdunn** [comment]
Do you mean the shift from 8 to 9? If so, component 8 is renamed as segment 9 after pilon polishing. Visualising the output graphs in  [Bandage](https://rrwick.github.io/Bandage/) will give you an idea of the changes being made.

Is there a reason you want to maintain the IDs?

Sorry to be commenting on everything, just trying to help as Unicycler's saved me so much time.

**Comment by semiramisCJ** [comment]
We would like to maintain the IDs because we select some contigs (from the assembly) for further analysis using the contig ID in the log file. 

I will check the output in Bandage; thanks for the suggestion, Steve.

**Comment by stevenjdunn** [comment]
Most of the information in the log file is included in the headers written in the final file.

You can quickly see all contig headers in a file with:
`grep ">" assembly.fasta`
To get a quick idea on how many are circularised, length etc. 

For replicon typing check out Torsten Seemann's [Abricate](https://github.com/tseemann/abricate). Really neat tool, also does resistance and a bunch of other stuff.
`abricate --db plasmidfinder assembly.fasta`

Let me know if there's any other info you need to get at, good luck!

**Comment by semiramisCJ** [comment]
Thank you very much, Steven. I didn't know about Abricate; but it sounds good! Thanks!
