### ISSUE TITLE
bowtie2 version parsing is incorrect.

### ISSUE THREAD

**Issue by andersgs** [rrwick/Unicycler#13]
Hi Ryan.

When using version 0.3.1, I noticed that bowtie2 was reported as having version 4.9.3. Seemed odd, so I checked. 

This is what I get when running `bowtie2 --version` on barcoo:

```
/usr/local/bowtie2/2.2.9-gcc/bin/bowtie2-align-s version 2.2.9
64-bit
Built on barcoo-m.vlsci.unimelb.edu.au
Mon Jun 27 10:33:54 AEST 2016
Compiler: gcc version 4.9.3 (GCC)
Options: -O3 -m64 -msse2  -funroll-loops -g3 -DPOPCNT_CAPABILITY
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
```

It seems `unicycler` is picking up the `gcc` version?

This is what is in the `unicycler` log:

```
Dependencies:
  Program         Version    Status
  spades.py       3.8.0      good
  makeblastdb     2.2.30+    good
  tblastn         2.2.30+    good
  bowtie2-build   4.9.3      good
  bowtie2         4.9.3      good
  samtools        1.3.1      good
  java            1.8.0_25   good
  pilon           1.21       good
```

You can replicate by running it on barcoo.

A.

**Comment by rrwick** [comment]
Good eye - I just noticed the same thing a couple of days ago! It was indeed grabbing the GCC version.

I had recently fixed this in Unicycler's development branch, but that branch is not in a great working state at the moment, so I moved just this fix into master. Should be good now!
