### ISSUE TITLE
low coverage regions in hybrid assembly

### ISSUE THREAD

**Issue by phiweger** [rrwick/Unicycler#134]
hi,

what happens when — in a hybrid assembly — there are regions w/ no/ low coverage by illumina? bc/ i observe a lot of snps in these regions and suspect that they are nanopore artifacts and need nanopore only polishing.

thank you.

**Comment by Kirk3gaard** [comment]
I guess the assembly breaks unless you use the "bold" mode.

**Comment by rrwick** [comment]
@phiweger, you are correct. If the Illumina graph is broken up and some sequence is missing:
1. Unicycler may struggle more (it works best with nice, complete Illumina graphs) and is more likely to make a mistake.
2. The missing sequence will be filled in with Nanopore-only sequence, which explains your extra SNPs.

Other than getting more Illumina reads (and more evenly distributed reads - TruSeq helps), there is no great way around this problem. One trick that can help a bit is to pre-prepare a Nanopore-only assembly that you've put through Nanopolish. Then use the `--existing_long_read_assembly` option provide this to Unicycler. Read more here: #93. This should result in higher quality filled-in Nanopore-only sequence, so fewer SNPs. But even after Nanopolish, SNPs are to be expected.

Ryan
