### ISSUE TITLE
Inconsistent SPAdes assemblies

### ISSUE THREAD

**Issue by sjackman** [rrwick/Unicycler#162]
I'm getting different results when I specify different sets of values for `--kmers`, even when the same best value of *k* is selected.

```console
$ unicycler -t16 --mode=bold --no_correct --keep 3 -o $*.unicycler -1 1.fq.gz -2 2.fq.gz -s s.fq.gz
K-mer   Contigs   Dead ends   Score      
   27                         too complex
   47       345          17      1.53e-04
   63       165           9      5.51e-04
   77        85           7      1.31e-03
   89        50           5      2.86e-03
   99        44           5      3.25e-03
  107        30           6      4.17e-03
  115        24           6      5.21e-03
  121        17           4      9.80e-03
  127        18           3      1.11e-02 ← best
```

```console
$ unicycler -t16 --kmers=63,127 --mode=bold --no_correct --keep 3 -o $*.unicycler -1 1.fq.gz -2 2.fq.gz -s s.fq.gz
K-mer   Contigs   Dead ends   Score   
   63       166          11   4.63e-04
  127        18          19   2.65e-03 ← best
```

The same value of *k*=127 was selected for both, but the assemblies differ.
```
  127        18           3      1.11e-02 ← best
  127        18          19   2.65e-03 ← best
```

The final assemblies after the rest of the Unicycler pipeline differ quite a bit. The first has 2 contigs, and the second has 7 contigs.

Any idea what's going on or how I can trouble shoot this issue?

**Comment by sjackman** [comment]
In a multi-*k* assembly, is any information carried over from each SPAdes assembly for one value of *k* to the next value of *k* (like IDBA for example), or are each of the assemblies independent?

**Comment by asl** [comment]
Sure, SPAdes uses all the information from all lower k-mers.

**Comment by sjackman** [comment]
Thanks for confirming, Anton!

From the source code, I believe Unicycler is running SPAdes once with multiple values of *k*.
https://github.com/rrwick/Unicycler/blob/ea9f1dc5d7f7b9798ae68f32e622abbe4a6671e3/unicycler/spades_func.py#L362-L363

That clears that up!
