### ISSUE TITLE
Unicycler wont run - Samtools too old

### ISSUE THREAD

**Issue by peflanag** [rrwick/Unicycler#171]
Hi,

Unicycler has stopped working for me. It says samtools is too old but it is not. This is the error I have gotten. Any help would be great! Also, I noticed that the name of my comupter has changed for some reason. It was MinION-iMac but now its (base) MinION-iMac

Im not sure if this is the issue?

Error: Unspecified error with Unicycler dependencies
(base) MinIONs-iMac:~ minion$ samtools -v
dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /miniconda3/bin/samtools
  Reason: image not found
Abort trap: 6
(base) MinIONs-iMac:~ minion$

**Comment by peflanag** [comment]
Just to update, the (bash) before my computer name is gone but unicycler still wont run because it says same tools is too old yet its updated. Can anyone help?

**Comment by surtlab** [comment]
Hi,

I just ran into the same issue with conda and unicycler:

Dependencies:
  Program         Version   Status  
  spades.py       3.12.0    good    
  racon           1.3.2     good    
  makeblastdb     2.7.1+    good    
  tblastn         2.7.1+    good    
  bowtie2-build   2.3.4.3   good    
  bowtie2         2.3.4.3   good    
  samtools        ?         too old 
  java            11.0.1    good    
  pilon           1.23      good    

Error: Unspecified error with Unicycler dependencies

**Comment by peflanag** [comment]
Hey, so I just deleted conda/miniconda/anaconda from the machine and removed the environment from the path and installed unicycles and all the other dependencies independently and it’s fine. I read online that conda can cause conflicts with non conda installed programs. Not really sure if that makes sense. I’m a biologist and not a computer science guy but it worked for me!

**Comment by martinmchugh** [comment]
I had this problem too. Worked out it was to do with different versions of samtools in different conda channels, you need to specify the bioconda channel to get the right version for unicycler.

So remove your current unicyler env:
conda remove --name unicyclerENV --all

Then recreate the env from the bioconda channel:
conda create -n unicyclerENV -c bioconda unicycler

**Comment by peflanag** [comment]
Cheers. I meant to close the thread and say I managed to install without conda in the end! But it must have slipped my mind!

**Comment by rgladstone** [comment]
I created a conda env for unicycler but it had the same issue as @surtlab (samtools ? too old). The fix was to then install the specific version of samtools to that env

conda create -n unicyclerENV -c bioconda unicycler
conda activate unicyclerENV
conda install -c bioconda samtools openssl=1.0

**Comment by rmzelle** [comment]
Just in case other folks run into issues with this as well, `$ conda create -n unicycler -c bioconda unicycler` also resulted in a samtools error for me when trying to run unicycler:

```
Dependencies:
  Program         Version   Status  
  samtools        ?         too old`
```

I fixed this by installing the latest version of samtools with:

```
$ conda activate unicycler
$ conda install -c bioconda samtools=1.11

...

The following packages will be UPDATED:

  samtools                                            1.7-1 --> 1.11-h6270b1f_0
```

Alternatively, specifying a newer version of samtools right away worked as well (`$ conda create -n unicycler2 -c bioconda unicycler samtools=1.11`).

**Comment by jpaganini** [comment]
Hi guys, 

I hope you are having a nice day.

I was experiencing the same issue. So, I tried to run samtools from my unicycler environment and got the following error message: 

`samtools -h`
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

Apparently it is a known issue with this tool.  Followed issue https://github.com/ndaniel/fusioncatcher/issues/110  and created  a soft link for this library:

`ln -s ~/miniconda3/envs/unicycler/lib/libcrypto.so.1.1 ~/miniconda3/envs/unicycler/lib/libcrypto.so.1.0.0`

('unicycler' is the name of my conda env, obviously could be different)
This fixed the issue!

I hope this can help!

Cheers,

**Comment by tamascogustavo** [comment]
> Just in case other folks run into issues with this as well, `$ conda create -n unicycler -c bioconda unicycler` also resulted in a samtools error for me when trying to run unicycler 0.4.8:
> 
> ```
> Dependencies:
>   Program         Version   Status  
>   samtools        ?         too old`
> ```
> 
> I fixed this by installing the latest version of samtools with:
> 
> ```
> $ conda activate unicycler
> $ conda install -c bioconda samtools=1.11
> 
> ...
> 
> The following packages will be UPDATED:
> 
>   samtools                                            1.7-1 --> 1.11-h6270b1f_0
> ```
> 
> Alternatively, specifying a newer version of samtools right away worked as well (`$ conda create -n unicycler2 -c bioconda unicycler samtools=1.11`).

This one worked for me ! Thanks
