### ISSUE TITLE
SPAdes error - Failed to determine offset

### ISSUE THREAD

**Issue by osilander** [rrwick/Unicycler#173]
I'm getting an error from SPAdes - `Failed to determine offset! Specify it manually and restart, please!`
If I specify the offset manually when calling SPAdes there is no issue, but I can't figure out how to set this when SPAdes is called from Unicycler. I know this has been raised as an issue with SPAdes [before](https://github.com/ablab/spades/issues/37) and it would be great to have the explicit option in the call to Unicycler.
Cheers.

**Comment by xiulinwan** [comment]
Have you solved this problem? I also have this problem.

**Comment by sjtrauber** [comment]
Were either of you able to solve this problem?

**Comment by rrwick** [comment]
I know this is an old issue, but I'm working on a new version of Unicycler (v0.5.0) and there is now a workaround for this problem: #279 :smile:

**Comment by xiulinwan** [comment]
谢谢来信，已收到
