### ISSUE TITLE
Quick question: Can I use Unicycler for plastid genomes?

### ISSUE THREAD

**Issue by OnlyHigh** [rrwick/Unicycler#177]
Hi Ryan, 
I was wondering if I could use Unicycler for the assembly of plastid genomes (cpDNA and mtDNA), 
Any especial consideration to take into account? 
PD, Should I "extract" the reads from the mt and cpDNA and then assembly or use them all? 

Cheers, 
Luis Alfonso.

**Comment by gaworj** [comment]
Hi Luis,

I've sucessfully used Unicycler for organellar genomes assembly. You can use extracted reads for better performance and to speed up with assembly time.

Bests,
Jan

**Comment by OnlyHigh** [comment]
Thanks Jan (I didn't saw the comment before)
