### ISSUE TITLE
Could you add --memory option for Spades

### ISSUE THREAD

**Issue by ConstantinV** [rrwick/Unicycler#19]
Hello!
Thank you for this tool!
I have 'out of memory' message while running Spades with a lot of threads (-t 144).
What do you recommend to solve this issue? 

The Best regards.

**Comment by rrwick** [comment]
I too have noticed that SPAdes can encounter problems with too many threads, so I've made Unicycler limit SPAdes to 32 threads (https://github.com/rrwick/Unicycler/commit/cdd075386e8c71d8c9f603ba8e5eea2d9e3589e6). Unicycler can still use more for other parts of its pipeline. The change is in the development branch of Unicycler and should make its way into the next bug-fix release.

It's not the most elegant or robust fix for this problem, but seeing as how Unicycler is only intended for bacterial genomes, I do think 32 threads is plenty! I may revisit this one in the future and try to be more clever about it - e.g. looking at the system memory and choosing thread limits more intelligently.

Thanks!

**Comment by Buuntu** [comment]
I get a `malloc` error even with 8 threads and 60 GB of memory available.  Seems like a lot to get an out of memory message, going to try it now on 4 threads to see if that works.  Any other setting I can change to get Spades to use less memory?
