### ISSUE TITLE
Pilon using more threads than allocated on cluster

### ISSUE THREAD

**Issue by swlong** [rrwick/Unicycler#198]
I realize this may ultimately be a pilon issue and not inherent to unicycler, but my cluster administrator has recently asked me to look into why pilon apparently spikes its cpu utilization and grabs as many as 31 cores when I've limited the overall threads per job to 4 (due to cluster restrictions) on my unicycler jobs. 

There's a "--threads" option for pilon which is supposedly defaulted to 1 and "experimental" but it doesn't appear that I can pass a threads value to pilon. For that matter, the fact that I'm running unicycler and designating that I have 4 threads available (-t 4) doesn't seem to be impacting pilon either. Has anyone else experienced this behavior on a cluster using the Torque/PBS job submission system? My administrator is rather unhappy with the behavior. 

I'm running Unicycler v0.4.3, in this case doing short read only assemblies, and the following dependencies:

Dependencies:
```
  Program         Version     Status     Path                                       
  spades.py      3.10.1      good       /share/apps/spades/3.10.1/bin/spades.py    
  racon                       not used                                              
  makeblastdb     2.6.0+      good       /share/apps/blast/2.6.0/bin/makeblastdb    
  tblastn         2.6.0+      good       /share/apps/blast/2.6.0/bin/tblastn        
  bowtie2-build   2.2.3       good       /share/apps/bowtie2/2.2.3/bin/bowtie2-build
  bowtie2         2.2.3       good       /share/apps/bowtie2/2.2.3/bin/bowtie2      
  samtools        1.9         good       /share/apps/samtools/1.9/bin/samtools      
  java            1.8.0_111   good       /share/apps/jdk/latest/bin/java            
  pilon           1.22        good       /share/apps/bin/pilon-1.22.jar             
  bcftools                    not use
```
                                            
Also happy to punt this over to Pilon as well, if that's the best course of action. Appreciate any help. 

Best,
S. Wesley Long

**Comment by rrwick** [comment]
Hi, Wesley! I know this is old, but I'm working on a new version of Unicycler (v0.5.0) and trying to address/close some of the many unanswered issues.

Anyway, I've decided to remove Pilon from Unicycler as it's no longer my preferred polisher (see #283), so I'm going to close this issue now :smile:
