### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by nekrut** [rrwick/Unicycler#2]
We would like to wrap Unicycler as a galaxy (http://usegalaxy.org) tool. We resolve tool dependecies via conda (https://docs.galaxyproject.org/en/master/admin/conda_faq.html). 

- are you planning on creating a conda package, or
- can you tell us what the deps are. from what I gather so far these are:
   * zlib1g-dev
   * bowtie2
   * pilon
   * blast
   * samtools
   * spades

Thanks for writing a great utility!

**Comment by rrwick** [comment]
I wasn't planning on writing a conda package, but I'll let you know if I do!

Those dependencies look about right. There's also Java (for Pilon), Python 3.4+ (to actually run Unicycler) and a C++ compiler to build it. I'm not sure if you need to make the distinction between command line tools that Unicycler calls (SPAdes, Bowtie2, Pilon, SAMtools and BLAST) and those needed for compiling Unicycler (zlib).
