### ISSUE TITLE
Corrected or Raw Nanopore reads?

### ISSUE THREAD

**Issue by ConstantinV** [rrwick/Unicycler#20]
Hello!

Could you recommend what kind of nanopore reads will be suitable for analysis raw reads or corrected reads by nanocorr ? 

Thanks!

**Comment by rrwick** [comment]
Unicycler will happily take uncorrected Nanopore reads. If you have a lot of reads, then I'd suggest subsampling them based on quality - excluding really bad reads can be helpful. But a typical decent Nanopore read (about 80-95% accuracy) is fine and doesn't need correction.

Also, passing your reads through [Porechop](https://github.com/rrwick/Porechop) can help a bit by trimming adapters and splitting some chimeric reads.
