### ISSUE TITLE
Pilon not catching all SNPs in the final assembly.

### ISSUE THREAD

**Issue by stevenjdunn** [rrwick/Unicycler#200]
Hi,

I was wondering if anyone else has run into issues with variants persisting in their final output assembly? 

I have several fully circularised E. coli genomes that successfully finish their Pilon rounds (some far ahead of the upper limit), but are still found to contain a number of variants when mapping their constituent short reads. 

Additional polishing does seem to clear up the vast majority of these, so I'm wondering if it's perhaps the maximum number of SNP correction rounds that's causing the problem? Could we get an option to manually increase the limit?

Cheers,
Steven.

**Comment by rrwick** [comment]
I've come to prefer other polishing tools to Pilon (some of my favourites are Polypolish, POLCA, HyPo and NextPolish), so I've decided to remove Pilon polishing from Unicycler. Since this issue no longer applies, I'll close it now.
