### ISSUE TITLE
SPAdes read error correction

### ISSUE THREAD

**Issue by piotr-piotr-majewski** [rrwick/Unicycler#201]
Hi,

I am completely newbie here and just encountered some issues with Unicycler run with Ubuntu.

Dependencies:
  Program         Version   Status  
  spades.py       3.11.1    good    
  racon           1.4.0     good    
  makeblastdb     2.6.0+    good    
  tblastn         2.6.0+    good    
  bowtie2-build   2.3.4.1   good    
  bowtie2         2.3.4.1   good    
  samtools        1.7       good    
  java            11.0.3    good    
  pilon           1.23      good    
  bcftools                  not used

SPAdes read error correction (2019-07-15 15:15:56)
--------------------------------------------------
    Unicycler uses the SPAdes read error correction module to reduce the number of errors in the short read before SPAdes assembly. This can make the assembly faster and simplify the assembly graph structure.

Error: SPAdes crashed! Please view spades.log for more information.

**Comment by piotr-piotr-majewski** [comment]
unfortunately there is no spades.log file created after the crash. any help would be appreciated :)

**Comment by piotr-piotr-majewski** [comment]
it turns out that short-read input should be **fastq.gz** instead of **gz**

**Comment by mccmccc** [comment]
> 你好，
> 
> 我在这里完全是新手，刚刚在 Ubuntu 上运行 Unicycler 时遇到了一些问题。
> 
> 依赖项： 程序版本状态 spades.py 3.11.1 良好 racon 1.4.0 良好 makeblastdb 2.6.0+ 良好 tblastn 2.6.0+ 良好 bowtie2-build 2.3.4.1 良好 bowtie2 2.3.4.1 良好 samtools 1.7 良好 java 11.0.3 良好 pilon 1.23 好的 bcftools 没用过
> 
> ## SPAdes 读取错误修正 (2019-07-15 15:15:56)
> ```
> Unicycler uses the SPAdes read error correction module to reduce the number of errors in the short read before SPAdes assembly. This can make the assembly faster and simplify the assembly graph structure.
> ```
> 
> 错误：SPAdes 崩溃了！请查看 spades.log 了解更多信息。

hello, I meet problem also. Did you solve this? I need your help, my friend. Thanks
