### ISSUE TITLE
pilon polishing: --fix parameter in hybrid assemblies

### ISSUE THREAD

**Issue by etvedte** [rrwick/Unicycler#202]
I was going through the unicycler_polish.py script to try and identify what unicycler's implementation of pilon tries to fix in hybrid long+short read assemblies. There is a print message             on line 417:

print('Not fixing local misassemblies', flush=True)

I didn't see this message in unicycler log, so I'm assuming that if you give unicycler long+short reads, it will use pilon's default of --fix all. Is this correct?

**Comment by rrwick** [comment]
Sorry, but I've decided to retire `unicycler_polish`, as it's quite out-of-date, so this issue no longer applies and I'll close it now.
