### ISSUE TITLE
Increasing Java memory?

### ISSUE THREAD

**Issue by tnn111** [rrwick/Unicycler#212]
Is there any way of increasing the memory allocated to Java for Pilon? I have it fail because of not enough stack space.

Thanks!

**Comment by swlong** [comment]
Yes. Check out https://github.com/rrwick/Unicycler/issues/63 - a simple and elegant solution is described there.

**Comment by rrwick** [comment]
The current version of Unicycler (v0.5.0) no longer includes Pilon polishing (see #283), so Java/Pilon are no longer dependencies. I'll therefore close this issue now.
