### ISSUE TITLE
Single reads used in error correction but not in assembly

### ISSUE THREAD

**Issue by bwemheu** [rrwick/Unicycler#214]
I made a test and processed some reads (paired and unpaired reads; (PF = Paired_Forward, PR= Paired_Reverse, UF and UR unpaired forward and reverse) with spades in error_correction mode without assembly and compared the number of reads to the number of corrected reads produced by Unicycler:

Using SPAdes
"spades.py --only-error-correction -1 PF.fastq.gz -2 PR.fastq.gz -s UF.fastq.gz -s UR.fastq.gz --meta -t 6 -m 32 -o error_correction"

I got (counted the number of lines with zgrep):
PF.fastq.00.0_0.cor.fastq.gz:4099780
PR.fastq.00.0_0.cor.fastq.gz:4099780
P_unpaired.00.0_0.cor.fastq.gz:34392
UF.fastq.00.0_1.cor.fastq.gz:211720
UR.fastq.00.0_2.cor.fastq.gz:7672

Unicycler (I joined the two files with unpaired reads before running unicycler).
"unicycler -1 PF.fastq.gz -2 PR.fastq.gz -s SE.fastq.gz -o assembly -t 6"

I got (counted the number of lines with zgrep):
corrected_1.fastq.gz:4099780
corrected_2.fastq.gz:4099780
corrected_u.fastq.gz:34392

Based on this, unicycler ignored all original unpaired reads although I specified them and they were listed in the command while running unicycler.

**Comment by rrwick** [comment]
I have decided to remove the read-error-correction step from Unicycler's pipeline in the newest version (v0.5.0), as I don't think it's helpful for a QCed read set. Since this issue no longer applies, I'm going to close it now.
