### ISSUE TITLE
[Feature Request] Changing the RAM limit

### ISSUE THREAD

**Issue by bwemheu** [rrwick/Unicycler#215]
Hi,

It would be great to include the -m parameter from spades. We are running unicycler on some metagenomes and simply need more memory than 250Gb.
Thanks.

Best,
Bernd

**Comment by stevenjdunn** [comment]
You could try changing line 364 of [spades_func.py](https://github.com/rrwick/Unicycler/blob/master/unicycler/spades_func.py) from:
`command = [spades_path, '-o', out_dir, '-k', kmer_string, '--threads', str(threads)]`

To:
`command = [spades_path, '-o', out_dir, '-k', kmer_string, '--threads', str(threads), '-m', '1024']`

**Comment by rrwick** [comment]
The new version of Unicycler (v0.5.0):
* includes `-m 1024` by default when calling SPAdes.
* has a `--spades_options` option were you can set `-m` to any value you'd like :smile:

**Comment by stokajian** [comment]
Facing this issue with plassembler
 2023-08-11 15:29:27.580 | ERROR    | plassembler.utils.input_commands:check_dependencies:215 - SPAdes not found.
We need to pass the above for it to find Spades?
Thank you
