### ISSUE TITLE
Issues with java_path

### ISSUE THREAD

**Issue by elainemmontes** [rrwick/Unicycler#216]
Hi,

I'm attempting to reproduce methodology for a genetics course and am having trouble with Unicycler: specifically with java_path.

I'm getting the following dependencies output: 
Dependencies:
  Program         Version   Status
  spades.py       3.13.1    good
  racon           1.4.7     good
  makeblastdb     2.9.0+    good
  tblastn         2.9.0+    good
  bowtie2-build   2.3.5     good
  bowtie2         2.3.5     good
  samtools        1.9       good
  java                      **bad**
  pilon           1.23      good
  bcftools                  not used

I've tried using two versions of Java (1.8.0_77, 1.8.0_171) 
with the path option " --java_path /share/pkg/jdk/1.8.0_171/bin/" from system install of java as well as environment version "--java_path /share/pkg/condas/2018-05-11/envs/unicycler_0.4.8_py37/bin/java"

When I remove java from the latter, the java status becomes "not found."

**Comment by stevenjdunn** [comment]
Try using the output from `which java`

You could also create a conda environment for Unicycler which should install all dependencies in a container, with `conda create --name Unicycler unicycler`. I find this is neater on my system as there are some dependency conflicts between Unicycler and other packages.

**Comment by rrwick** [comment]
Since Pilon-polishing is being removed from Unicycler (see #283), Java is no longer a dependency. That dodges this problem, so I'll close the issue :smile:
