### ISSUE TITLE
The method strip_read_extensions() is overly greedy.

### ISSUE THREAD

**Issue by cerebis** [rrwick/Unicycler#22]
Since modern OS don't impose a constraint on the use of ".", it would perhaps be better if this method did not assume it is only used to demarcate suffixes and greedily remove them all. The dot character seems to increasingly creep into file name usage.

With the current approach, files can be named in such a way that both R1 and R2 become identically named. Unicycler does not appear to notice the resulting name clash.

The event of a name clash should probably be detected (IE stripped R1 != stripped R2) and perhaps the stripping method could be rewritten with less possibility for unintended actions.

**Comment by rrwick** [comment]
Thanks for spotting this. I've just pushed a commit (https://github.com/rrwick/Unicycler/commit/275373b4453528106c843031dcf62a5ae6d41a36) to the development branch which I think fixes this. It should make it into the next bug-fix release.

It now only strips off known extensions. I also tried to make it tolerate particularly odd filenames. I don't think it will mess up on anything but the most evil filenames! Thanks!
