### ISSUE TITLE
Issue with pilon

### ISSUE THREAD

**Issue by sushanta26** [rrwick/Unicycler#222]
Hi
I am facing problem at polishing step ,pilon is not working in my system showing error with sample data set.

Here is the command I have used 

./unicycler-runner.py -1 /home/sdas/Desktop/Software/unicycler/Unicycler/sample_data/short_reads_1.fastq.gz -2 /home/sdas/Desktop/Software/unicycler/Unicycler/sample_data/short_reads_2.fastq.gz -o output_dir  --spades_path /home/sdas/Desktop/Software/Spades/SPAdes-3.13.1/spades.py --bowtie2_path /home/sdas/Desktop/Software/bowtie2-2.3.5.1-linux-x86_64/bowtie2 --bowtie2_build_path /home/sdas/Desktop/Software/bowtie2-2.3.5.1-linux-x86_64/bowtie2-build  --samtools_path /home/sdas/Desktop/Software/samtools-1.9/samtools --makeblastdb_path /home/sdas/Desktop/ANI/blast/ncbi-blast-2.9.0+/bin/makeblastdb --tblastn_path /home/sdas/Desktop/ANI/blast/ncbi-blast-2.9.0+/bin/tblastn

The Error I am getting 
Dependencies:
Traceback (most recent call last):
  File "./unicycler-runner.py", line 21, in <module>
    main()
  File "/home/sdas/Desktop/Software/unicycler/Unicycler/unicycler/unicycler.py", line 67, in main
    check_dependencies(args, short_reads_available, long_reads_available)
  File "/home/sdas/Desktop/Software/unicycler/Unicycler/unicycler/unicycler.py", line 809, in check_dependencies
    pilon_path_and_version(args.pilon_path, args.java_path, args)
  File "/home/sdas/Desktop/Software/unicycler/Unicycler/unicycler/misc.py", line 1121, in pilon_path_and_version
    version = out.decode().split('Pilon version ')[-1].split()[0]
IndexError: list index out of range

**please guide me where I am making mistake or I am missing something.**

thanks

**Comment by rrwick** [comment]
Sorry, but I've decided to remove Pilon polishing from Unicycler (#283), so I'm going to close this issue as it's no longer relevant for the current version.
