### ISSUE TITLE
[Feature Request] --isolate option for SPAdes

### ISSUE THREAD

**Issue by ilnamkang** [rrwick/Unicycler#223]
Hi,

SPAdes 3.14.0 introduced "--isolate" option for assembly of standard datasets with good coverage (>100x).

May I expect that I would be able to use "--isolate" option in Unicycler in the future?

Thanks.

**Comment by rrwick** [comment]
The new version of Unicycler (v0.5.0) is now compatible with current versions of SPAdes, and that includes using the `--isolate` option. Thanks!
