### ISSUE TITLE
No mention of dependency "ale"

### ISSUE THREAD

**Issue by tseemann** [rrwick/Unicycler#226]
Root cause of #190

**Comment by mbhall88** [comment]
The dependency does seem to be listed in the docs for [`unicycler_polish`][docs]. However, I was wondering yesterday whether the conda recipe should be updated to include this dependency?

[docs]: https://github.com/rrwick/Unicycler/blob/master/docs/unicycler-polish.md

**Comment by rrwick** [comment]
I'm working on a new version of Unicycler at the moment (v0.5.0) which removes a lot of old pieces that I don't think should be used in 2022. That includes `unicycler_polish`, so this one shouldn't apply anymore!
