### ISSUE TITLE
Makefile for minimap is overly specific

### ISSUE THREAD

**Issue by cerebis** [rrwick/Unicycler#23]
Compilation options supplied to GCC are overly specific by using ```march=native```. In heterogeneous execution environments, builds on one system will fail to run on machines with differing architecture. 

It would be better if this was left to documentation and perhaps the default made no CPU specification or instead used ```mtune=native```, so as to avoid errors from the shared lib that end-users may not easily interpret.

**Comment by rrwick** [comment]
Thanks for the feedback - I've just pushed this change into the development branch and it will make its way into the next bug-fix release!
