### ISSUE TITLE
Rotate circular contigs in standalone unicycler_polish?

### ISSUE THREAD

**Issue by bjreisman** [rrwick/Unicycler#239]
Thanks for your work on this software. I like using the standalone `unicyclcer_polish` module to polish assemblies generated using long-read assemblers. I noticed in the unicycler documentation that the full unicycler pipeline will rotate circular contigs between rounds of polishing (if I'm reading it correctly). Watching the unicycler_polish log, it doesn't appear that circular contigs are rotated in the standalone module. Is there a way to get the standalone module to recognize contigs as circular and rotate them as in the full pipeline? Alternatively, it would be great to be able to set a flag to rotate all/some contigs between polishing rounds.

**Comment by rrwick** [comment]
Thanks, but I've decided to remove the very out-of-date `unicycler_polish` command from Unicycler, so I will now close this issue :smile:
