### ISSUE TITLE
feature suggestion/question

### ISSUE THREAD

**Issue by fifthguy** [rrwick/Unicycler#24]
Hi, 

I've been doing something similar with the combination of short and long reads, and with further pilon refinement (just that instead of a single pass I used 2-3 pilon passes). In my some of the I had more than one short read dataset ie. one set of 150 x 2 and another one of 250 x 2 to which I then added nanopore reads. As the spades. Theoretically Expander (if I understand it accurately) would have best performance with a monodisperse or a very narrow insert size so I didn't want to simply cat the two datasets into a single read library; in these cases SPAdes actually provides the command line options to input several short read libraries -- would it feasible and would it make sense to add a similar feature to Unicycler? (From the SPAdes command line it seems possible) but I'm not sure for the rest of the pipeline.

Sorry for writing this here and thanks! (If you find this post inappropriate here, I will close the issue immediately)

**Comment by rrwick** [comment]
Thanks for the suggestion!

This feature (allowing multiple Illumina library inputs) is on my to-do list, so I may get around to it eventually! It would be easy to make it work with SPAdes, as SPAdes already handles this. However, elsewhere in Unicycler I assume a single insert size distribution, so I would need to change a few things to make it work with multiple libraries. I'll keep this issue around as an enhancement.

That being said, whenever I've dealt with a similar situation (two read sets for the same isolate) in SPAdes, I've found that just using the better set of the two worked fine. I haven't encountered a scenario where I got a significantly improved assembly from using both at once. I'm sure it is possible though, especially if the two input sets are both low depth.

**Comment by jflot** [comment]
Any progress on this? It would be really great to be able to input several short-read libraries in Unicycler.

**Comment by rrwick** [comment]
Sorry, but this is probably not something I'm going to implement, so I'll close this issue now 🙁  Unicycler is unlikely to be receiving any major new features, see the [2022 update in the README](https://github.com/rrwick/Unicycler#2022-update).

Unicycler doesn't lean too much on insert size assumptions, so as long as your two libraries are reasonably similar, you can just cat the short reads together and assemble them as a single library (see #270).
