### ISSUE TITLE
Short contigs

### ISSUE THREAD

**Issue by andrewjpage** [rrwick/Unicycler#25]
Thanks for the brilliant tool.  The only small thing I've noticed is that there are sometimes very short contigs in the final assembly:

```
>9 length=3 depth=0.73x
ACA
>10 length=1 depth=0.73x
C
```

Would it be possible to automatically filter these out (perhaps anything less than the median short read length)?

**Comment by andrewjpage** [comment]
I should say that yes I know that there is an option --min_fasta_length, but it would be nice to have it default to an automatic sensible value if not set by the user or something.

**Comment by rrwick** [comment]
You're not the first person to suggest increasing the `--min_fasta_length` default :smile:

I've just made a new release of Unicycler which (along with a bucketload of other changes) increases the default to 100. Thanks!
