### ISSUE TITLE
Spades 3.12, 3.13 and 3.9 crashes but not 3.14

### ISSUE THREAD

**Issue by lalalagartija** [rrwick/Unicycler#251]
Hi, 

--- UPDATE ---
I tricked unicycler to work with version 3.14.1 editing the misc.py file and it outputs an assemblage. Can I trust it ?
-------------------

Is there a way to use unicycler with Spades version 3.14 ? It is the only version that do not crash on my data for an obscure reason. I tried to start at read error correction or at assembly without correction and I always get this error.

Thank you very much in advance, 

One spades log file for example : 
`Command line: /home/oar-jobs/tools/src/SPAdes-versions/SPAdes-3.12.0-Linux/bin/spades.py        -1      /tshared/data/Genomics_rawdata/2020-12-08_DY0_DY1_M4_MegaPleistocene_MimiRiviere_illumina/CedratDY1/DY1_FDSW202615984-1r_HJVTGDSXY_L2_1.fq.gz   -2      /tshared/data/Genomics_rawdata/2020-12-08_DY0_DY1_M4_MegaPleistocene_MimiRiviere_illumina/CedratDY1/DY1_FDSW202615984-1r_HJVTGDSXY_L2_2.fq.gz -o      /home/rigou/Cedrats_Siberi2020/CedratDY12020_unicycler/spades_assembly/read_correction  --threads       32      --only-error-correction --phred-offset  33

System information:
  SPAdes version: 3.12.0
  Python version: 2.7.16
  OS: Linux-4.19.0-10-amd64-x86_64-with-debian-10.7

Output dir: /home/rigou/Cedrats_Siberi2020/CedratDY12020_unicycler/spades_assembly/read_correction
Mode: ONLY read error correction (without assembling)
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/tshared/data/Genomics_rawdata/2020-12-08_DY0_DY1_M4_MegaPleistocene_MimiRiviere_illumina/CedratDY1/DY1_FDSW202615984-1r_HJVTGDSXY_L2_1.fq.gz']
      right reads: ['/tshared/data/Genomics_rawdata/2020-12-08_DY0_DY1_M4_MegaPleistocene_MimiRiviere_illumina/CedratDY1/DY1_FDSW202615984-1r_HJVTGDSXY_L2_2.fq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset: 33
  Corrected reads will be compressed
Other parameters:
  Dir for temp files: /home/rigou/Cedrats_Siberi2020/CedratDY12020_unicycler/spades_assembly/read_correction/tmp
  Threads: 32
  Memory limit (in Gb): 250

======= SPAdes pipeline started. Log can be found here: /home/rigou/Cedrats_Siberi2020/CedratDY12020_unicycler/spades_assembly/read_correction/spades.log

===== Read error correction started. 

== Running read error correction tool: /home/oar-jobs/tools/src/SPAdes-versions/SPAdes-3.12.0-Linux/bin/spades-hammer /home/rigou/Cedrats_Siberi2020/CedratDY12020_unicycler/spades_assembly/read_correction/corrected/configs/config.info

The program was terminated by segmentation fault
=== Stack Trace ===

== Error ==  system call for: "['/home/oar-jobs/tools/src/SPAdes-versions/SPAdes-3.12.0-Linux/bin/spades-hammer', '/home/rigou/Cedrats_Siberi2020/CedratDY12020_unicycler/spades_assembly/read_correction/corrected/configs/config.info']" finished abnormally, err code: -11

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
`

**Comment by stevenjdunn** [comment]
Does `spades.py --test` run to completion on the older versions? Are you using a package manager to install software?

Newer versions of SPAdes were specifically blocked in the most [recent commit](https://github.com/rrwick/Unicycler/commit/372307cae7647bf96f4aaa0be1f7f904adf81cce) - which is what you've undone in misc.py. I would suggest getting the recommended versions to play nicely, or try a different assembly method.

**Comment by rrwick** [comment]
I'm working on a new version of Unicycler (v0.5.0) which has been designed to work with modern versions of SPAdes, so this issue should no longer apply :smile:

In case anyone's curious, starting with v3.13.1, SPAdes stopped outputting all _k_-mer graphs, so even if they could be made to work with older versions of Unicycler (v0.4.9 or earlier), the [ideal _k_-mer selection](https://github.com/rrwick/Unicycler#spades-assembly) wasn't working.
