### ISSUE TITLE
unicycler.vcf_func.CannotMakeVcf:

### ISSUE THREAD

**Issue by hafizmtalha** [rrwick/Unicycler#259]
I'm running the unicycler with --vcf option enabled. assembly step works fine but error comes at vcf building step. any idea how to resolve this?
Traceback (most recent call last):
  File "/usr/bin/unicycler", line 11, in <module>
    load_entry_point('unicycler==0.4.8', 'console_scripts', 'unicycler')()
  File "/usr/lib/python3/dist-packages/unicycler/unicycler.py", line 227, in main
    make_vcf(final_assembly_vcf, args, final_assembly_fasta, insert_size_1st, insert_size_99th)
  File "/usr/lib/python3/dist-packages/unicycler/vcf_func.py", line 110, in make_vcf
    raise CannotMakeVcf('mpileup/bcftools encountered an error: ' + err.decode())
unicycler.vcf_func.CannotMakeVcf: 'mpileup/bcftools encountered an error: /bin/sh: 1: Syntax error: "(" unexpected\n'

**Comment by rrwick** [comment]
Sorry, but `--vcf` is being removed from Unicycler (see #271) so I'm going to close this issue.
