### ISSUE TITLE
small contigs in assembly.fasta

### ISSUE THREAD

**Issue by xthua** [rrwick/Unicycler#26]
hi, i tried to run unicycler combined the data of illumina and pacbio. The log file showed the size of chromosome is about 4M. however, only 800k or smaller fragment was showed in the assembly.fasta. the bold mode already used.  

Xiaoting

**Comment by rrwick** [comment]
That's a tough one to troubleshoot without looking at your data... there are a lot of reasons why an assembly could fail to complete.

Previously, if the Illumina read set was poor, that could seriously impact the final assembly. But I've just made a new release of Unicycler which changes a lot. In particular, it can do long-read-only assembly, which it also does during hybrid assembly to better deal with bad Illumina reads.

Could you try the new version and see if it helps? Note that you'll need to install [Racon](https://github.com/isovic/racon) which is now a dependency. Let me know if it improves!

If it's still not good, I'm happy to investigate further by trying your assembly myself. Assuming there are no data privacy issues, I could make a Dropbox directory in which you could upload your reads.

**Comment by xthua** [comment]
hi, I tried the new version of unicycler. and the error information was listed below:

Finding overlaps with minimap... success
  600,825 overlaps

Assembling reads with miniasm... terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 1840) > this->size() (which is 0)

Best wishes,

Xiaoting

**Comment by rrwick** [comment]
Ouch - that's not a nice crash! It's a new one to me and looks to be in the miniasm assembly.

I'm afraid I can't investigate without trying it myself. Is it possible for you to share your reads with me? Are there data privacy issues? I could make a Dropbox directory and share it with you (I would need the email linked to your Dropbox account). Or some other cloud storage like Google drive, if you prefer. Or else if you can host them somewhere I could download them. Let me know what works for you.

**Comment by rrwick** [comment]
This issue is pretty old, so I'm going to close it now, but please let me know if you are still running into this crash, and I can look into it more.

Ryan
