### ISSUE TITLE
Unicycler hangs on polishing step

### ISSUE THREAD

**Issue by valery-shap** [rrwick/Unicycler#262]
Hello,

I saw #140 and #153 but still have questions.
There is the bug with 0.4.8 and 0.4.9 from conda installation.
@PertuyF what do you mean with starting the assembly again in #140 ? Should I change smth with the data?
@soda460 Thank you very much for the advice with removing 'incomplete' suffix. But I have the only one sam file in the Pilon_polish dir and the name of sam is '4_paired_alignments.sam'.
Unicycler is stuck on the forth round of polishing.
Is the 'right' recipe
 installing 0.4.9 from source locally with make and run it from folder and use the dependencies from new conda env? Or all programs including dependencies should be not from conda?
version 0.4.4 works fine with this data. But the quality of the assembly is rather worse.

Best regards,
Valery

**Comment by PertuyF** [comment]
Hi 🙂
Old issue, too bad this one is not fixed yet...
What I meant is just to abort assembly when it is stalling, and start it again. At that time the stalling bug was reported to be random, as rerunning with same files and parameters sometimes succeeded.

**Comment by valery-shap** [comment]
Thank you very much for reply!
I've already run it with 0.4.9 from source and all other in conda env. And it works perfect.
Before with 0.4.8 from conda I had 4 samples and 3 of them were hanging. Suspiciously often to be random)
and all of these 3 had very good quality of assembly (in cleaned.gfa) like 1 circular chromosome or 1 chromosome circular and circular plasmids. I've seen somewhere here that the problem could be with fasta file not containing 80 letters in line.

Best regards,
Valery
