### ISSUE TITLE
Polishing assembly with Pilon Unable to polish assembly using Pilon: bowtie2-build failed to build an index

### ISSUE THREAD

**Issue by nbutyrate** [rrwick/Unicycler#265]
Hi,

i ran the following

unicycler -1 1_S45_R1_001.fastq.gz.clipped_R1.fq -2 1_S45_R1_001.fastq.gz.clipped_R2.fq -l Bt172.subreads.fastq.gz -o output_dir

got the assembly output (i.e. assembly.fasta) but i think  the polishing step did not work as i got the following notification

Polishing assembly with Pilon
Unable to polish assembly using Pilon: bowtie2-build failed to build an index

please let me know how to correct this

**Comment by rrwick** [comment]
Sorry, I'm not sure what went wrong here, but I'm going to close this issue because the upcoming version of Unicycler drops Pilon polishing altogether. See #283 for more details.
