### ISSUE TITLE
How to determine coverage of Oxford Nanopore reads

### ISSUE THREAD

**Issue by termithorbor** [rrwick/Unicycler#266]
Hi all,

how can I get a rough idea what the coverage of my Oxford Nanopore sequencing is? 
Is something like number of bases sequenced (e.g. Gb or Mb) divided by genome size sufficient enough?

This information seems to be quite important for chosing between Unicycler and Trycycler.

Thanks in advance

**Comment by rrwick** [comment]
Yes, you can use read bases divided by genome sizeto get Nanopore read depth. It may not be _perfect_ (e.g. if the reads are biased towards deletions or some reads don't align), but it's good enough for most purposes :smile:
