### ISSUE TITLE
v0.4.9 -- spades.py  3.13.1 too new 

### ISSUE THREAD

**Issue by unitsmanolis** [rrwick/Unicycler#269]
You can delete this post, thanks

**Comment by unitsmanolis** [comment]
I installed spades 3.6.2 and python 3.5. Spades works alone ...

but even if in unicycler I use --spade_path (v3.6.2) and the tool report "spades good", unicycler crash the same ...

**Comment by rrwick** [comment]
FYI: I'm working on Unicycler v0.5.0 now, which will work with modern versions of SPAdes.
