### ISSUE TITLE
two pairs of short reads

### ISSUE THREAD

**Issue by herber4** [rrwick/Unicycler#270]
is there a way to input more than one pair of short reads?

**Comment by rrwick** [comment]
Not directly into Unicycler, no. However, you could just combine them:
```bash
cat a_reads_1.fastq.gz b_reads_1.fastq.gz > combined_reads_1.fastq.gz
cat a_reads_2.fastq.gz b_reads_2.fastq.gz > combined_reads_2.fastq.gz
```
And then give them to Unicycler as a 'single' read set. This will probably work best if the two read sets have not-too-different read lengths and insert sizes.

Ryan
