### ISSUE TITLE
options: --keep 2, --vcf

### ISSUE THREAD

**Issue by unitsmanolis** [rrwick/Unicycler#271]
Hi,

I'm using the option --keep 2 but I can not find in the output directory the file. I would like to keep the "alignments.bam" or something similar in sam/bam.

Will you validate the --vcf option?

Example:

unicycler -1 R1.fastq.gz -2 R2.fastq.gz -o output --mode normal --vcf --keep 2 --spades_tmp_dir ${tmp}

Best!

**Comment by rrwick** [comment]
Sorry, but the `--vcf` option was always a bit half-baked. I'm working on a new version of Unicycler now and have decided to remove that option, so any variant calling will need to be separately, outside of Unicycler.

Ryan
