### ISSUE TITLE
Difficulty using --existing_long_read_assembly

### ISSUE THREAD

**Issue by SandersonHaley** [rrwick/Unicycler#276]
I am trying to do a hybrid assembly using an existing long read assembly. This is the command I am using: unicycler -t 15 -o testout -1 SRR13712361_1.fastq.gz -2 SRR13712361_2.fastq.gz --mode bold --existing_long_read_assembly SRR13712361_LR.fasta
The error I am getting is: Error: --existing_long_read_assembly can only be used with hybrid assemblies

What am I doing wrong?

**Comment by rrwick** [comment]
Sorry, that error message wasn't as clear as it could be. The problem is that you need to supply long reads (`-l`) as well. I've changed the error message to hopefully be more clear:
```
Error: --existing_long_read_assembly requires both short and long read inputs
```
