### ISSUE TITLE
unused/unassembled long reads

### ISSUE THREAD

**Issue by hbadrane** [rrwick/Unicycler#277]
Do Unicylcer keep track of unused/unassembled long reads? Is there an output file for filtered out, unused/unassembled long reads?

Thanks.

**Comment by rrwick** [comment]
No, I'm afraid it does not. Unicycler uses long reads in a few different ways at different steps, so it would be tricky to even define what is meant by an unused read. E.g. what about reads used in the miniasm assembly step but not in the long-read-bridging step?

If it helps, you could run Unicycler with `--keep 2` and use the `long_read_alignments.sam` file to see which reads it did use in the long-read-bridging step.

Ryan
