### ISSUE TITLE
Telomeres

### ISSUE THREAD

**Issue by hbadrane** [rrwick/Unicycler#278]
I used Unicycler on a yeast 12.3m genome, and was impressed the assembly was close to a total assembly with ONT long reads (60x - 180x) and Illumina Short reads.
However, telomeres were absent from the assembly, how to deal with this to have as much complete chromosomes as possible? knowing that telomeres have a lot of repeats?
This also joins the question of tracking removed reads posed earlier : [unused/unassembled long reads #277](https://github.com/rrwick/Unicycler/issues/277)

**Comment by rrwick** [comment]
Unicycler will often remove repeats from the ends of linear replicons, and this is an unfortunate consequence of how it was built with circular bacterial replicons in mind. I don't think this will change, so I'm afraid the answer is simply that Unicycler is probably not the best assembler for your data. I'd recommend trying a long-read-first assembly approach, e.g. [Trycycler](https://github.com/rrwick/Trycycler) plus short-read polishing.

Ryan
