### ISSUE TITLE
add an option in Unicycler to pass down --phred-offset 33 to SPAdes

### ISSUE THREAD

**Issue by jflot** [rrwick/Unicycler#279]
Sometimes SPAdes fails to autodetect the PHRED offset of Illumina reads:
```
0:00:00.002     1M / 3M    INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
0:00:00.017     1M / 3M    ERROR   General                 (main.cpp                  :  89)   Failed to determine offset! Specify it manually and restart, please!
```
(see e.g. https://github.com/ablab/spades/issues/37)
To solve this problem, it would be great to add an option in Unicycler to pass down --phred-offset 33 to SPAdes.

**Comment by rrwick** [comment]
I'm working on a new version of Unicycler now, which will include `--spades_options` so you can run Unicycler like this:
```
unicycler-runner.py -1 reads_1.fastq.gz -2 reads_2.fastq.gz -o assembly --verbosity 2 --spades_options "--phred-offset 33"
```

If you're keen, you can try this new option by installing Unicycler from the main branch of GitHub. Or if you'd rather wait for the release (v0.5.0), it shouldn't be far off!

Ryan
