### ISSUE TITLE
Java problem

### ISSUE THREAD

**Issue by caonetto** [rrwick/Unicycler#28]
Hi I am trying to run unicycler but I get this error:
**Dependencies:
  Program         Version   Status 
  spades.py       3.9.1     good
  makeblastdb     2.6.0+    good
  tblastn         2.6.0+    good
  bowtie2-build   2.3.0     good
  bowtie2         2.3.0     good
  samtools        1.3.1     good
  java            ?         too old
  pilon           1.22      good

Error: Unspecified error with Unicycler dependencies**

Is this a problem with my Java?? This is the output of java -version

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

Thanks!

**Comment by andersgs** [comment]
Check out issue #17

**Comment by caonetto** [comment]
Thanks Anders, 
I am a bit unexperienced with programming, could you please explain me with more details
the changes you did to fix the problem?

Thanks!!!

**Comment by caonetto** [comment]
Anyone that could help me? I would really appreciate it!! :)

**Comment by rrwick** [comment]
This should now be fixed in the current version (v0.4.0). See issue #17 for more info.
Thanks for spotting the bug!
