### ISSUE TITLE
How to make hybrid assembly of a viral genome

### ISSUE THREAD

**Issue by sekhwal** [rrwick/Unicycler#282]
Hi,
I am looking to make Hybrid assembly of a viral genome. I have got paired-end reads from Illumina and long reads from MinION from a viral sample. Please suggest if Unicycler can be used for viral genome assembly. Also, please let me know if I need to trim the data before making assembly. Currently, I am using Unicycler for bacterial hybrid genome assembly.
Thank you!

**Comment by rrwick** [comment]
While Unicycler might work (you're welcome to try), it was built with bacterial genomes in mind, so probably isn't optimal for viral genomes. In particular, Unicycler does better with circular sequences than linear sequences.

Assuming you have decent Nanopore read depth, I'd recommend trying a long-read-first approach to hybrid assembly: get the best possible assembly you can using only your Nanopore reads and then use your Illumina reads to polish the assembled sequence.

Ryan
