### ISSUE TITLE
Releasing Unicycler v0.5.0 on conda as a package?

### ISSUE THREAD

**Issue by wanyuac** [rrwick/Unicycler#284]
Hi Ryan,

Would it be possible to have a conda package of Unicycler v0.5.0? I failed to install Unicycler through `pip3 install git+https://github.com/rrwick/Unicycler.git` on the HPC that I am using for compatibility issues.

Thanks

**Comment by hoelzer** [comment]
Hi, I finally managed to install unicycler 0.5.0 (in a Docker container) via

```bash
conda update -y -n base -c defaults conda
conda install -y -c anaconda python>=3.10
conda install -y mamba
mamba install -y -c bioconda python=3.10 unicycler=0.5.0 && conda clean -a
```

The container is also publicly available if this helps:

```
docker pull nanozoo/unicycler:0.5.0--652d482
```

**Comment by meono** [comment]
I see the linux version is already there. would be great to have the osx version updated too (or a noarch version if that's reasonable).

**Comment by wanyuac** [comment]
The conda package of Unicycler 0.5.0 is available: https://anaconda.org/bioconda/unicycler. Therefore, this issue is closed.
