### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Hashable'

### ISSUE THREAD

**Issue by manolis80** [rrwick/Unicycler#287]
Hi,

I have this error with spade when I'm running Unicycler

`AttributeError: module 'collections' has no attribute 'Hashable'`

I installed Unicycler using conda

Best

**Comment by kayobianco** [comment]
Hello everyone,

I have the same problem, can the developer help us?

**Comment by missuse** [comment]
There appears to be a problem with the conda recipe for unicycler 0.5. However manually installing dependencies from conda and then installing Unicycler from github works without problems.

**Comment by rrwick** [comment]
There seems to be an incompatibility with SPAdes and Python v3.10: https://github.com/ablab/spades/issues/863

That issue thread suggests that a new version of SPAdes is coming soon with a fix, which will hopefully solve the problem. But until then, running with Python v3.9 should get around it.

Ryan
