### ISSUE TITLE
Short and long reads from different isolates

### ISSUE THREAD

**Issue by termithorbor** [rrwick/Unicycler#289]
Hi,

what would be the best approach for assembling the genome when the short and long reads come from different isolates?

Thanks in advance :)

**Comment by rrwick** [comment]
Well. my initial answer is don't do that :smile: If the read sets are from different isolates, then I don't expect them to assemble well together!

But if you need to for some reason, I'd try both a short-read-first approach like Unicycler and a long-read-first approach like Trycycler+polishing. A Unicycler assembly will probably look more like the genome in the short-read set, and a Trycycler+polishing assembly may look more like the genome in the long-read set.

For either approach, the closer the two isolates are, the better I'd expect the assembly to work. Good luck!

Ryan
