### ISSUE TITLE
Long read-only assembly

### ISSUE THREAD

**Issue by DNAsaurus** [rrwick/Unicycler#29]
Just at the start it says:

> Unicycler is a assembly pipeline for bacterial genomes. It uses Illumina reads **and/or long reads (PacBio or Nanopore)** to produce complete and accurate assemblies.

but later on in the manual it becomes obvious that short reads are not optional like long reads.
Is it possible to use Unicycler with only long (corrected Nanopore) reads?

**Comment by rrwick** [comment]
Long-read-only assembly is now very much an option in Unicycler!

I was still editing the README a few days ago, and it may have contained conflicting information for a while. But I just made a new release, and I think the README is now consistent and makes sense.

Also, long-read-only assembly should work fine with uncorrected long reads. It's probably a good idea to do some QC on the reads so you're not giving Unicycler total junk, but normal Nanopore reads (say about 80-95% accuracy) should be fine. Corrected reads should also work, but aren't necessary. Thanks for bringing this up - I just added a comment to the README saying that uncorrected reads are okay.
