### ISSUE TITLE
Why pilon.jar and not just pilon

### ISSUE THREAD

**Issue by andersgs** [rrwick/Unicycler#3]
Hi Ryan.

Just running a test with 0.2 (great docs, btw!!). We have a script called `pilon` on the PATH, which calls `pilon.jar` with specific memory requirements. Is there any reason to run `pilon.jar` directly? I was looking at the code, and it did not strike me that this was the case.

Cheers.

A.

**Comment by rrwick** [comment]
No, there's not a reason, so I've just pushed up a change (to the master branch) which makes Unicycler accept either a `pilon` executable or a `pilon.jar` file. As before, it will look automatically if you don't specify anything, or else you can use the `--pilon_path` option to say where to look.

Thanks for the idea! Give a try and let me know if there are any issues.

**Comment by andersgs** [comment]
Thank you, Ryan. Works a treat!
