### ISSUE TITLE
Failing in the Loading Reads step. IndexError: list index out of range??

### ISSUE THREAD

**Issue by caonetto** [rrwick/Unicycler#30]
I am getting the following error in the Loading Reads step:
Loading reads (2017-07-03 07:52:59)
114,292 / 114,292 (100.0%) - 148,471,758 bpTraceback (most recent call last):
  File "/mnt/jiao/nanopore/Unicycler/unicycler-runner.py", line 21, in <module>
    main()
  File "/mnt/jiao/nanopore/Unicycler/unicycler/unicycler.py", line 134, in main
    read_dict, read_names, long_read_filename = load_long_reads(args.long)
  File "/mnt/jiao/nanopore/Unicycler/unicycler/read_ref.py", line 126, in load_long_reads
    original_name = line.strip()[1:].split()[0]
IndexError: list index out of range

Any ideas?

Thanks!

**Comment by rrwick** [comment]
I know this is an old, closed issue, but if anybody else hits this problem, I think it's because you're using an old version of Unicycler. This one should be fixed in this commit: 868fd012199fa07fa17371b9ca60ec0f9664f5d4.

Ryan
