### ISSUE TITLE
version 0.4.0 not in pypi ?

### ISSUE THREAD

**Issue by tseemann** [rrwick/Unicycler#31]
```
unicycler --version
Unicycler v0.3.1

pip3 install --upgrade unicycler
Requirement already up-to-date: unicycler in /home/linuxbrew/.linuxbrew/lib/python3.6/site-packages
```

**Comment by tseemann** [comment]
My mistake, I see you don't support pypi. This worked just as "RTFM" intended :)

```
pip3 install git+https://github.com/rrwick/Unicycler.git
```

**Comment by rrwick** [comment]
Someday when Unicycler isn't under so much active development, I'll try to get it in PyPI!

**Comment by sjackman** [comment]
It's in Homebrew/science now.
:beer: `brew install homebrew/science/unicycler`

**Comment by tseemann** [comment]
Thanks @sjackman - i didn't realise you can write the formula the way you did with `:python3` and setup etc.

**Comment by sjackman** [comment]
That was my first formula like that too.
