### ISSUE TITLE
miniasm assembly failed

### ISSUE THREAD

**Issue by abs-yy** [rrwick/Unicycler#321]
Hi @rrwick , thank you for the great software!

I've been assembling plasmid sequences with very low coverage ONT duplex reads (5~20 reads) and error correcting with simplex reads later on. However unicycle, or miniasm to be specific, keeps on failing at the assembly step. I presume  #38 is related to this issue. Running miniasm directly on the reads/paf file with `miniasm -c 2 -e 2`, `miniasm -c 2`, `miniasm -e 2` or `miniasm -2` results in a single unitig, with the ones with `-c` resulting in a x1.2 longer unitig. Increasing duplex reads would certainly be the best approach but we are having trouble with increasing the duplex read ratio (for reasons unknown).

You mentioned in #38 that you are planning to add an option to feed options directly to miniasm, would this be implemented in the near future? 

Best,

**Comment by rrwick** [comment]
Sorry, but I haven't added that feature, so there isn't a way to pass custom options to miniasm. And with a very small number of reads, I don't think Unicycler's miniasm-bridging method will be very effective, even if you do get it to run.

So I think the best answer is to just turn off that part of the pipeline using `--no_miniasm`. Unicycler will still carry out its long-read bridging step, which has a better chance of working with a small number of reads.

Ryan
