### ISSUE TITLE
Should input reads be trimmed before use

### ISSUE THREAD

**Issue by karinlag** [rrwick/Unicycler#33]
Hi!

This looks like a great tool. I am likely to use it on bacterial Illumina reads. Should the reads be trimmed for quality and adapters before use?

**Comment by tolot27** [comment]
It depends on the sequencer you are using. For MiSeq/MiniSeq and NextSeq it is not necessary. Even for HiSeq data I got slightly better assemblies with unfiltered reads.

**Comment by rrwick** [comment]
Sorry to come so late to this one. I've had similar experiences to Mathias, where trimming/quality filtering Illumina reads isn't usually necessary. However, I do occasionally encounter a bad Illumina set with lots of very short fragments where many reads have hit the adapter on the far side of the fragment. For those bad sets, adapter trimming definitely does help.

I'm a fan of [Trim Galore](https://github.com/FelixKrueger/TrimGalore) which makes it pretty easy. Here's an example command I would use:
`trim_galore --paired --quality 10 reads_1.fastq.gz reads_2.fastq.gz`

This command will take care of adapters (though a good Illumina set is likely to have very few) and trim off low quality parts of reads. By using a very conservative quality threshold of 10, I only want Trim Galore to trim based on quality when reads get _really_ bad. For a good read set, this command changes very little about the reads.
