### ISSUE TITLE
SPAdes v4.0.0

### ISSUE THREAD

**Issue by natchaphon602** [rrwick/Unicycler#338]
How could I run unicycler with newest SPAdes version? Am I need to config some files?

**Comment by rrwick** [comment]
The latest release of Unicycler (v0.5.1, created just a couple minutes ago) allows for SPAdes v4. Might take a bit of time to make it into Bioconda, so [install from source](https://github.com/rrwick/Unicycler#install-from-source) if you need it ASAP. That being said, I haven't seen any obvious benefit from using SPAdes v4, so you can keep using SPAdes v3.15 if you'd like.

Ryan
