### ISSUE TITLE
getUnicyclerGraphStats.py script

### ISSUE THREAD

**Issue by NicolasNesi** [rrwick/Unicycler#339]
Hello,

I am looking for the script getUnicyclerGraphStats.py referenced in some papers. It is supposed to be part of Unicycler, but I can't find it. 

Is anyone has a link for it? 

Thanks

**Comment by rrwick** [comment]
I'm not sure, but I think that might be Ben Vezina's script, not part of Unicycler. I have no memory of it, anyway!

But if you wanted it for counting dead ends in the graph, I made a custom tool for that:
https://github.com/rrwick/GFA-dead-end-counter

And there's some more explanation on this blog post:
https://rrwick.github.io/2023/02/21/dead-ends-for-assembly-qc.html

Ryan

**Comment by NicolasNesi** [comment]
Yes, it is from Vezina papers. Thank you for the links!

Nicolas
