### ISSUE TITLE
using Ion torrent and nanopore reads

### ISSUE THREAD

**Issue by supanthee** [rrwick/Unicycler#34]
I am trying to use unicycler for my reads obtained from Ion PGM and nanopore. However, it fails at spades reads error correction.

Any suggestions how I could overcome this problem

Thanks
Suresh

Command: /usr/local/bin/unicycler -s smithPGM.fastq -l smithNP-PCBio-cor.fastq --no_rotate --no_miniasm -o smithunicycler1

Unicycler version: v0.4.0
Using 4 threads

The output directory already exists and files may be reused or overwritten:
  /Users/Suresh/Desktop/smithunicycler1

Dependencies:
  Program         Version     Status  
  spades.py       3.10.1      good    
  racon                       not used
  makeblastdb                 not used
  tblastn                     not used
  bowtie2-build   ?           good    
  bowtie2         ?           good    
  samtools        1.5         good    
  java            1.8.0_131   good    
  pilon           1.22        good    
  bcftools                    not used

SPAdes read error correction (2017-07-19 14:14:43)
    Unicycler uses the SPAdes read error correction module to reduce the number
of errors in the short read before SPAdes assembly. This can make the assembly
faster and simplify the assembly graph structure.

Command: /usr/local/bin/spades.py -s /Users/Suresh/Desktop/smithPGM.fastq -o /Users/Suresh/Desktop/smithunicycler1/spades_assembly/read_correction --threads 4 --only-error-correction
Error: SPAdes read error correction failed

**Comment by rrwick** [comment]
Sorry, but I've never tried Unicycler with Ion Torrent reads. All of its short read assembly was designed with Illumina reads in mind. You could try skipping the read error correction (with the `--no_correct` option). Or if the reads really do need error correction, maybe some other program will do a better job than SPAdes. If you could correct the reads first, then give them to Unicycler with `--no_correct`. But again, I have no experience in the matter, so I'm not sure if you'll have any luck.

If you have any success, please post it here for other users to read. Thanks!

Ryan
