### ISSUE TITLE
unicycler's aligning reads seem to have stalled

### ISSUE THREAD

**Issue by kystensy** [rrwick/Unicycler#340]
When I ran the genome mix splicer, I went to the aligning reads step, and the progress was stuck at 89.9% for more than 12 hours. In Explorer, the cpu usage of the unicycler program kept changing. Is the program running properly? The unicycler version used is v0.5.0.

Program description：
Determining low score threshold (2024-08-17 17:55:50)
    Before conducting semi-global alignment of the long reads to the assembly graph, Unicycler must determine a minimum alignment score threshold such that nonsense alignments are
excluded. To choose a threshold automatically, it examines alignments between random sequences and selects a score a few standard deviations above the mean.

Automatically choosing a threshold using random alignment scores.

Random alignment mean score: 61.66
         standard deviation:  1.31
        Low score threshold: 61.66 + (7 x 1.31) = 70.86

Aligning reads (2024-08-17 17:56:24)
16,861 / 18,759 (89.9%)
[unicycler.log](https://github.com/user-attachments/files/16647074/unicycler.log)

**Comment by rrwick** [comment]
I'm not sure why the read alignment has stalled, but I can say with confidence that there is something terribly wrong with your data! I can see in the log that:
* Your Illumina assembly graph has tens of thousands of contigs - far too many for _E. coli_ (or any bacterial genome really).
* Your miniasm assembly was very fragmented and only 600 kbp - far too small for _E. coli_.

Perhaps you have contamination, e.g. multiple _E. coli_ genomes mixed together? Some investigation into what's wrong with your reads is warranted before using Unicycler (or any other assembler). Sorry!

**Comment by kystensy** [comment]
Thanks for your response, I will process the data again and run unicycler again.
