### ISSUE TITLE
assembly.fasta is empty?

### ISSUE THREAD

**Issue by swlong** [rrwick/Unicycler#36]
Started working on my third genome with Unicycler. First two worked well, ONT & Illumina data.

Took a stab at some old PacBio data. Everything seemed to work, but in the end, the assembly.fasta file that is generated is empty. Screenshot attached. Let me know what other log info might be helpful. 

<img width="369" alt="empty_fasta" src="https://user-images.githubusercontent.com/2158927/28468017-58892b18-6df7-11e7-8066-55d586c13cd5.PNG">

**Comment by rrwick** [comment]
Damn, I have no idea! All of the other files look good. Unicycler normally makes its `assembly.gfa` and `assembly.fasta` files at the end of its process, so I'm particularly confused that the gfa was made and the fasta wasn't. There also seems to be a 6 hour time difference between the two. Weird.

My only thought is that something has gone terribly wrong. Were there any error messages or crashes? If it behaves this way consistently, I'd been keen to check out the gfa file to see if there's anything obviously strange going on.

Ryan

**Comment by rrwick** [comment]
This issue is pretty old, so I'm going to close it now, but please let me know if you are still seeing this issue, and I can look into it more.

Ryan

**Comment by SeanBeagle** [comment]
I had this same problem and realized I was typing `grep > assembly.fasta | wc -l` without quoting the ">" and wiped everything out.  I wonder if swlong came in at 0900 to work.. tried to see how many contigs he had, and did something similar!

**Comment by nsarode-joyn** [comment]
I am having the same issue. I am trying to do Illumina only assembly on 3 sample sets. The first two worked just fine, but the third one created an empty assembly.fasta file. Based on the stdout (attached as log file), it appears that things started falling apart during the 'Creating contig bridges' step, even though unicycler doesn't really complain much. Am I correct in guessing that in case like this simply running spades with reference as guide is a better way to go?
[03-08-19_unicycler.log](https://github.com/rrwick/Unicycler/files/2946902/03-08-19_unicycler.log)

**Comment by swlong** [comment]
I like SeanBeagle's potential explanation, but I haven't seen this issue again either...
