### ISSUE TITLE
Error at minimap step Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by ggautreau** [rrwick/Unicycler#43]
Hello,

When I perform an hybrid assembly and a long read-only assembly too, an error occurs at minimap and miniasm step.

The error is : llegal instruction (core dumped)

Compilation is ok and all required tools are loaded.

Data used are the Shigella reads available here : https://github.com/rrwick/Unicycler/tree/master/sample_data

Have you any idea about the origin of this issue ?

Thank for your help.

**Comment by sergiarredondo** [comment]
Hi @ggautreau ,

In most cases it is a memory problem (at least in my experience). If you are running Unicycler in an HPC environment, I would try to request for more memory and see if the problem goes away.

**Comment by rrwick** [comment]
Hi Guillaume,

Did you have any luck with Sergio's suggestion? It could be a memory problem, but that sample read set is pretty small and shouldn't require much memory.

Another possibility is that the compute environment is heterogeneous and has different CPUs on different nodes. It may be that the node you compiled on has CPU instructions not available on the node which is running the code. Other users ran into issues with this, so I changed the Makefile (6058faa9611182958029a79a4d7c35fc59595aa9) to be less specific.

This change is in the just-released v0.4.1, so give that a try and see if it fixes the problem?

Ryan

**Comment by rrwick** [comment]
This issue is pretty old, so I'm going to close it now, but please let me know if you are still running into this crash, and I can look into it more.

Ryan
