### ISSUE TITLE
Unicycler Thinks Spades Version is Incorrect

### ISSUE THREAD

**Issue by conra91** [rrwick/Unicycler#45]
Hi. Trying to run unicycler locally on my laptop (Macbook Pro, MacOS Sierra) and when directed to the spades path (version 3.10.1-Darwin) using

` --spades_path /directory/directory/SPAdes-3.10.1-Darwin/bin/spades.py `

unicycler returns the error saying that the version of spades is too old. Cannot work out at all how to sort get past this bit so any advice would be great!

**Comment by rrwick** [comment]
Hmmm, either there's something not working with your copy of SPAdes or Unicycler is botching the parsing of the SPAdes version number. I tried to reproduce the issue myself, but couldn't.

Could you run `/directory/directory/SPAdes-3.10.1-Darwin/bin/spades.py -v` and let me know what the output is? I'd expect it to simply be: `SPAdes v3.10.1`

Ryan

**Comment by conra91** [comment]
Hi Ryan,

 

Yeah, when I run the –v command I get;

 

SPAdes v3.10.1

 

Any thoughts?

**Comment by rrwick** [comment]
Damn, I'm stumped! If SPAdes is returning a normal version output like that, I'm not sure why Unicycler is failing to parse it.

While looking at this, I have just tweaked the code a bit to parse the version using regex. You're welcome to try this latest change on the development branch (ac60f6092b9ae8947fc880bded1602d5819536e6), but seeing as how your SPAdes output looks normal to me, I'm pessimistic it will solve your problem.

The issue may lie in the `spades_path_and_version` function in the `misc.py` file. If you don't mind getting your hands a bit dirty, I'd be curious to know what happens in you made the following change. After the `out = out.decode()` line in that function, add:
```python
print(out)
quit()
```

Then reinstall Unicycler and run it. It should show the SPAdes version output (exactly what Unicycler is seeing) and then quit. Might be informative.

And if you're not in the mood to debug and just want a crude fix, you could try changing that whole function to this:
```python
def spades_path_and_version(spades_path):
    return spades_path, '3.10.1', 'good'
```

That would effectively skip the version check by hard-coding the result.

**Comment by conra91** [comment]
Hey Ryan,

Sorry for the delay getting back to you. So upon trying the steps above I believe it was actually an issue with SPades and Python versions. My default python3 was python3.6. However, SPAdes isn't yet compatible with it - this meant that even by forcing the version check, in unicycler SPades would still crash. May also explain why the version check was coming back with an error as the incorrect version of python was being used?

Curiously, if I manually specified python3.5 to run Unicycler, SPades would crash (and the whole process fail) but if I simply opted to run the spades.py in isolation (e.g. `python 3.5 ./spades.py)`) the procerss would run. Unsure if that means there is some issue in unicycler utilising the specific version of python specified by the user? I'm still incredibly new to all of this, so I'm probably wrong!

Regardless, I messed about with my python settings so that python 3.5 is now my most up to date version, and running unicycler with that, in conjunction with SPAdes 3.10.1 seems to work! Let me know if you'd like me to try anything further that may help :)

**Comment by rrwick** [comment]
Interesting! I didn't realise that SPAdes hasn't added Python 3.6 support. I'm actually doubtful that Python 3.6 would break anything in SPAdes... they just seem to have hard-coded supported Python versions in their `spades_pipeline/options_storage.py` file, probably only wanting to allow what they've tested. But if you hacked that file to include 3.6, I predict it might work...

But back to Unicycler, I have just added (67a4a3c8b411ab9bbaaaf0ca5598e504f3ed8440) a check for the SPAdes Python error. That way, this scenario will give a more informative error message instead of the misleading 'too old' you were seeing.

Thanks for the help getting to the bottom of this one!
Ryan
