### ISSUE TITLE
error in pilon

### ISSUE THREAD

**Issue by efratca** [rrwick/Unicycler#46]
Hi,

I ran Unicycler and I got the following error message: 
"Pilon polish round 1
Unable to polish assembly using Pilon: Pilon encountered an error:
Invalid maximum heap size: -Xmx1G -XX:ParallelGCThreads=4 -jar
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit."

I modified the following  line in the script: "pilon_func.py":
 pilon_command = [args.java_path, '-Xmx1G -XX:ParallelGCThreads=4 '  '-jar', args.pilon_path]

Can you please help me solving that error in running pilon.

Thanks

**Comment by rrwick** [comment]
I'm not sure if follow. Were you getting an error before you modified that line of pilon_func.py? Why the modification?

Assuming you need those changes, my first thought is that the modified line isn't formatted correctly. Python subprocess needs each part of the command as a separate string in the list. Try this and see if it works instead:
```
pilon_command = [args.java_path, '-Xmx1G', '-XX:ParallelGCThreads=4', '-jar', args.pilon_path]
```

Let me know how you go!

Ryan

**Comment by efratca** [comment]
Thanks for the reply.
The former error was solved, now pilon starts to run (I used  -Xmx32G), but it falls with the error: “=>> PBS: job killed: vmem 48328523776 exceeded limit 41875931136”, the program is trying to allocate more vmem then it is asked (It is very close to the system vmem limit). How many vmem is needed for running pilon, and what can I do about that?
Thanks

**Comment by rrwick** [comment]
I wouldn't expect Pilon to need that much memory! :open_mouth:
What are you assembling and how big is the read set?

**Comment by efratca** [comment]
Thanks for the reply, eventually I succeeded to run it...

**Comment by rrwick** [comment]
Okay, glad to hear it!
