### ISSUE TITLE
Unpaired data: Problem with `-s` option

### ISSUE THREAD

**Issue by nekrut** [rrwick/Unicycler#50]
Obviously, using unpaired reads is quite suboptimal, but is some cases this is the one data available (albeit at high coverage). When using the `-u` option without `-1` and `-2` options Unicycler returns:

```
unicycler: error: the following arguments are required: -1/--short1, -2/--short2
```
Is it possible to make Unicycler happy with just the `-s` version?

**Comment by rrwick** [comment]
Hi Anton, I think Unicycler should be okay with unpaired-only inputs, as of v0.4.0. Are you using an older version? Can you grab a copy of the current release (v0.4.1) and try it again?

Ryan

**Comment by rrwick** [comment]
This issue is pretty old, so I'm going to close it now, but please let me know if you are still running into issues with unpaired-only datasets, and I can look into it more.

Ryan
