### ISSUE TITLE
SPAdes crashes on small paired-end read assembly

### ISSUE THREAD

**Issue by smehringer** [rrwick/Unicycler#52]
Hi @rrwick,

I am investigating if unicycler can be used for a slightly different purpose. I've been given some structural variants called with SNIFFLES from ONT reads and I also have Illumina paired reads available. I wondered if unicycler could be used for local reassembly of the investigated regions refining break points and catching false positives with the help of accurate Illumina reads.

I extracted 1034 short read fastq sequences (517 pairs) for a specific region of about 3000bp and called unicycler with default parameters for paired-end short reads (and 8 long reads). Dependencies are all reported to be ```good```. 

At the SPAdes assemblies section unicycler crashes because it cannot find the contigs.paths file. 
Stack Trace:
```
Traceback (most recent call last):
   File "Unicycler-0.4.1/unicycler-runner.py", line 21, in <module>
      main()
   File "/nfs/odinn/tmp/svenjam/Unicycler-0.4.1/unicycler/unicycler.py", line 87, in main
      args.no_correct, args.linear_seqs)
   File "/nfs/odinn/tmp/svenjam/Unicycler-0.4.1/unicycler/spades_func.py", line 178, in get_best_spades_graph
      insert_size_deviation=insert_size_deviation)
   File  "/nfs/odinn/tmp/svenjam/Unicycler-0.4.1/unicycler/assembly_graph.py", line 68, in __init__
      self.load_spades_paths(paths_file)
   File  "/nfs/odinn/tmp/svenjam/Unicycler-0.4.1/unicycler/assembly_graph.py", line 170, in load_spades_paths
       paths_file = open(filename, 'rt')
FileNotFoundError: [Errno 2] No such File or directory:  '/nfs/odinn/tmp/svenjam/sv.ins.1288233/output/spades_assembly/assembly/contigs_paths' 
```
I don't know if its the fault of my data, any idea? (Read pairs are identified by the same name-id)

Side note: If a treat the paired reads as unpaired by concatenating the two files and using unicycler with the s parameter (which of course doesn't make much sense for the assembly) the program doesn't fail.

**Comment by rrwick** [comment]
Thanks for the bug report! I've just pushed a fix (24d6adc)  to the [development branch](https://github.com/rrwick/Unicycler/tree/development) which I think will prevent the crash. You're welcome to pull from that branch and see if it's better! That fix should make its way into the next release (v0.4.2) in the not-too-distant future.

That being said, I don't officially support Unicycler doing anything but bacterial genome assemblies, so while you can try using it for other stuff, you're on your own :smile:

Ryan
