### ISSUE TITLE
crashed when entering polishing step and a few question about interpreting the result

### ISSUE THREAD

**Issue by a1204350** [rrwick/Unicycler#54]
Hi, thanks so much for this fantastic program and it has been useful since I found it! 

However, after I recently updated Bowtie2 via Linuxbrew, the program always stopped at the stage of polishing, and the below was the part of log file showing the error:

Polishing assembly with Pilon (2017-09-13 09:41:59)
    Unicycler now conducts multiple rounds of Pilon in an attempt to repair any remaining small-scale errors with the assembly.

Aligning reads to find appropriate insert size range...
  bowtie2-build 0_insert_size_check.fasta 0_insert_size_check.fasta
  bowtie2 -1 /home/zong/Desktop/LL34C/LL34Ctr_1.fq -2 /home/zong/Desktop/LL34C/LL34Ctr_2.fq -x 0_insert_size_check.fasta --local --fast-local --threads 24 -I 0 -X 5000 -S 0_alignments.sam
Unable to polish assembly using Pilon: Bowtie2 encountered an error:
Error parsing alignment policy setting 'SEED'; RHS must have 1 token, had 2.  Policy: 'SEED=0;SEEDLEN=20;DPS=15;ROUNDS=2;IVAL=S,1,0.75;SEED=0,22;DPS=10;ROUNDS=2;IVAL=S,1,1.75'
Error: Encountered internal Bowtie 2 exception (#1)
Command: /home/linuxbrew/.linuxbrew/bin/../Cellar/bowtie2/2.3.3/bin/bowtie2-align-s --wrapper basic-0 -x 0_insert_size_check.fasta --local --fast-local --threads 24 -I 0 -X 5000 -S 0_alignments.sam -1 /home/zong/Desktop/LL34C/LL34Ctr_1.fq -2 /home/zong/Desktop/LL34C/LL34Ctr_2.fq 
(ERR): bowtie2-align exited with value 1   

but at the beginning of dependencies check, it says "Good" in both bowtie2 and bowtie2-build. Could you please help me with this?

The question I'd like to ask below might be a bit obvious but really helpful for us to understand the result.

In the log file it shows something like below (from one of our previous runs)

Component   Segments   Links   Length      N50       Longest segment   Status    
    total        173     248   4,656,416   132,451           269,207             
        1        164     236   4,599,121   132,451           269,207   incomplete
        2          9      12      57,295    28,894            28,894   incomplete

1. We are wondering if this indicates the strain has ONLY one plasmid?

2. If a target gene, let's say blaKPC, is found to be tangled in the largest component (1, in this example), does this necessarily mean this target gene is definitely on the chromosome?

again, thanks so much!

**Comment by rrwick** [comment]
The first thing to check is whether Bowtie has the same issue outside of Unicycler. If you run the command on its own, what happens?
```
bowtie2 -1 /home/zong/Desktop/LL34C/LL34Ctr_1.fq -2 /home/zong/Desktop/LL34C/LL34Ctr_2.fq -x 0_insert_size_check.fasta --local --fast-local --threads 24 -I 0 -X 5000 -S 0_alignments.sam
```

If that crashes, then we can be sure Unicycler's not the problem - you'll have to sort out your Bowtie installation! If it does work, we can dig deeper.

And as a side note, you can skip polishing with the `--no_pilon` option. That will avoid the crash and save a lot of time. Is this an Illumina-only assembly or a hybrid assembly? I suspect polishing isn't too important for Illumina-only assemblies.

**Comment by rrwick** [comment]
Regarding the interpretation, the short answer is no, you can't assume that your largest component is the chromosome and the smaller one is a single plasmid. That's certainly possible, but there are other possibilities as well:
1) There are no plasmids - the chromosome has just assembled into two separate components.
2) The small component is made up of multiple plasmids which have common sequence with each other.
3) The large component, in addition to the chromosome, has one or more plasmids which share common sequence with the chromosome.

I find it helpful to view the graph in [Bandage](https://github.com/rrwick/Bandage). If there are very few dead ends in the graph, then you can probably rule out possibility 1. Based on the number of contigs, I'm going to assume this is an Illumina-only assembly. Interpreting Illumina assembly graphs can be tough and subjective, so you may not come to any solid answers. 

Ultimately you probably need to add long reads to be completely certain as to how many plasmids there are. There are tools to examine plasmids using only short reads, but none give bulletproof answers. I'd check out this paper for details and suggestions:
[On the (im)possibility of reconstructing plasmids from whole-genome short-read sequencing data](http://mgen.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000128)

**Comment by a1204350** [comment]
Thanks much for your reply! They will be really helpful for us.

I did what you suggested to find out if bowtie2 works with the command outside of Unicycler and it turned out bowtie2-2.3.3 still failed. However, after a rollback into bowtie2-2.3.2, it worked with the same command. So I suppose the problem might probably come from the latest release of bowtie2.

**Comment by rrwick** [comment]
Okay, good to hear. Since it's not a Unicycler bug, I'll close this issue now.
