### ISSUE TITLE
Error: SPAdes read error correction failed message, but error connection completed without error.

### ISSUE THREAD

**Issue by swlong** [rrwick/Unicycler#55]
Ran into an issue on my first attempt at using Unicycler with an unpaired Illumina short read FASTQ plus ONT long reads. 

I have an abundance of short reads (18M), which complete the error correction step using SPAdes without any obvious error. The SPAdes pipeline step completes, then the error "Error: SPAdes read error correction failed" is issued and Unicycler quits. 

To add insult to injury, the spades_assembly directory appears to be completely empty. I've attached the log, I can't figure out why the files wouldn't be there. Drive space is available. The total absence of output files might be responsible for the error, of course. However SPAdes showed files being written, so where did they go? 

Log file is here: 
[unicycler.log.txt](https://github.com/rrwick/Unicycler/files/1303195/unicycler.log.txt)

I attempted to rerun Unicycler after moving the FASTQ from a shared folder to the main partition of the VM, but it had the same error & result.

Best,
S. Wesley Long

**Comment by rrwick** [comment]
This feels familiar... I am about 60% sure that I've fixed this bug in v0.4.1 - can you give that version a try? If it still happens there, I'm happy to dig deeper.

Ryan

**Comment by swlong** [comment]
Argh! Apologies as I thought I had upgraded to 0.4.1 but had not. This is fixed in 0.4.1, it is running now. 

Thanks again,
Wesley
