### ISSUE TITLE
A few installation/setup issues

### ISSUE THREAD

**Issue by JCSzamosi** [rrwick/Unicycler#57]
Apologies if this is not the right forum. I couldn't find a listserv or google group.

When I run setup.py install, it installs fine, but ends with the following message:

`WARNING: some tools required by Unicycler could not be found: spades.py, pilon, bowtie2, bowtie2-build`

All of those tools are installed, and all but pilon are in my path (confirmed with `which`), so I don't know why it can't find them.

Additionally, pilon is, afaict, a .jar file, so I'm not sure how to sensibly add it to the path. Should I put a symlink just called "pilon" somewhere in my path?

**Comment by JCSzamosi** [comment]
Update: Creating symlinks to those files in /usr/local/bin/ instead of adding their containing directories to the path seems to have made the message go away.

**Comment by rrwick** [comment]
That's bizarre, I also don't know why Unicycler couldn't find the tools. I'm glad you found a workaround, though!

And regarding Pilon, you can just put the pilon jar file in a directory in your PATH. Even though it's not executable, Unicycler will look through the directories in your path to find anything that starts with 'pilon' and ends with '.jar'. If there are multiple hits, it uses the last (hopefully the latest version).

Ryan
