### ISSUE TITLE
Unicycler is now available on Galaxy at http://usegalaxy.org

### ISSUE THREAD

**Issue by nekrut** [rrwick/Unicycler#61]
@rrwick : if this is ok I'll add the following links to your README and provide a PR:

https://galaxyproject.github.io/training-material/topics/assembly/tutorials/unicycler-assembly/tutorial.html

https://galaxyproject.org/blog/2017-10-16-UnicyclerTutorial/

**Comment by rrwick** [comment]
It's certainly okay with me. Thanks very much for putting that together!
