### ISSUE TITLE
Passing multiple PE libraries into Unicycler

### ISSUE THREAD

**Issue by metagenomes** [rrwick/Unicycler#64]
SPAdes supports the passing in of multiple PE and MP files:

spades.py --pe1-1 lib1_forward_1.fastq --pe1-2 lib1_reverse_1.fastq \
    --pe1-1 lib1_forward_2.fastq --pe1-2 lib1_reverse_2.fastq \
    -o spades_output

I'd like to do the same with Unicycler, is there something I'm missing to be able to do this?

**Comment by rrwick** [comment]
No, you're not missing anything - Unicycler just can't do that. It's a common feature request, but I haven't gotten around to it yet :smile:

If your two libraries are quite similar (i.e. about same read length and insert size), then you should be able to just `cat` your read files together and give them to Unicycler as a 'single' library:
```
cat lib1_forward_1.fastq lib1_forward_2.fastq > reads_1.fastq
cat lib1_reverse_1.fastq lib1_reverse_2.fastq > reads_2.fastq
```

However, you said "PE and MP", so is one of your inputs a long insert mate pair library? Unicycler doesn't support those, so it probably isn't a good assembler choice for mate pair datasets. I'm not sure which assembler to recommend for that... I haven't encountered mate pair much in bacterial genomics and so don't have any experience.

Ryan

**Comment by metagenomes** [comment]
Thanks Ryan, I was specifically talking about PE libraries despite my vague question! I did wonder if I could pass them as a cat'd pair, but they're likely to differ on read length and insert size.

Apologies for posting a common feature request, should have looked at the previous issues more closely!

**Comment by rrwick** [comment]
Even with different read length or insert size, you _might_ get away with catting the files. It's worth a try, anyway.

That being said, when I've encountered this in the past using SPAdes (which does allow multiple libraries), I've usually found that the better of my two read sets assembles just as well as the combination of the two. So if one of your read sets is deeper or has more even read coverage than the other, you might do fine with that one alone.

**Comment by phbrito** [comment]
Hello,
If we concatenate reads from two (fairly similar) libraries as you suggested before does unicycler take care of duplicated reads or should we find a way to remove those before running unicycler?
Thanks!
Patrícia

**Comment by rrwick** [comment]
I've never actually tried using Filtlong on a short read set - it may work, but I make no guarantees! Generally speaking, there's no harm in having duplicated short reads. If I have _way_ too many short reads and it's slowing things down, I sometimes cut the set down by trimming with a stringent qscore. I like [Trim Galore](https://www.bioinformatics.babraham.ac.uk/projects/trim_galore/) for this sort of thing - set `--quality` and `--length` to large values to get rid of more reads.

**Comment by phbrito** [comment]
thanks for the suggestions! I wasn´t sure about Filtlong as it is described for long reads and will check Trim Galore
