### ISSUE TITLE
Java 9.0.1 too old?

### ISSUE THREAD

**Issue by dsladevt** [rrwick/Unicycler#65]
I have been trying to run a hybrid assembly with long (MinION) and short (Illumina) reads, but I am getting an error that Java is too old, although I just used Brew (brew cask install java) to install the latest version today (9.0.1).

Thanks in advance, and I can't wait to see what this can do for our genome after a stellar assembly with just long reads that only took an hour or so!

**Comment by rrwick** [comment]
That's no good! The reason is that Java used to do 1.6, 1.7, 1.8, etc but have now switches to 9.0. Unicycler was assuming the major version would be 1.

Anyway, I've fixed it and made a new minor release: v0.4.3. Grab the fresh version and it should work. If not, let me know!

Ryan

**Comment by dsladevt** [comment]
Ryan,

Thanks for being so fast with this.  I was able to use Java 1.8 while you were resolving this, and the genome looks amazing.  I can't tell you how bad these genomes were before, and now we can finally find all of the ORFs for virulence factor identification.  Huge fan, and thanks for making such great contributions to science!
