### ISSUE TITLE
problem running in virtual machine

### ISSUE THREAD

**Issue by rec3141** [rrwick/Unicycler#69]
I'm running Unicycler in virtualbox (because I can't get racon to compile on macosx), and SPAdes doesn't like that I've mounted my working directory using vboxfs (something about a bug in mmap). The SPAdes folks suggested I use '--tmp-dir' and point it to a virtualbox-local site like /tmp, and that works.

To get Unicycler to work in the vbox, I hacked spades_func.py to include '--tmp-dir /tmp' in the 'command' for SPAdes and it worked. You might want to include something like this, or an option to pass-through arguments to SPAdes.

thanks!

**Comment by rrwick** [comment]
That's very interesting. I've run into issues when running Unicycler on a network mount (SPAdes error correction failed) and I you might have solved it with `--tmp-dir`.

On a related note, I'm keen to try out alternative read error correction tools. This article is informative on the topic: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5563063/

If I find a better alternative, I might try to integrate it into Unicycler, at which point I'd stop using SPAdes read error correction and these issue would go away.

Ryan

**Comment by rrwick** [comment]
Also, regarding getting Racon to compile on a Mac, I had to use GCC instead of the Clang compiler which comes with Xcode.

There are probably multiple ways of doing it, but here's what I did:
* Install GCC v5 with Homebrew: `brew install gcc@5`
* In a directory of your choice, make symlinks to GCC v5:
```
ln -s /usr/local/bin/gcc-5 cc
ln -s /usr/local/bin/gcc-5 gcc
ln -s /usr/local/bin/g++-5 g++
ln -s /usr/local/bin/g++-5 c++ 
```
* Then whenever you want to use GCC instead of Clang (e.g. before compiling Racon), add the directory with your symlinks to the front of your path: `export PATH=/path/to/gcc5_symlinks_dir:"$PATH"`

**Comment by kapsakcj** [comment]
Hi @rec3141 ,

I too am [experiencing the same issue](https://github.com/rrwick/Unicycler/issues/82) that you mentioned and I was wondering if you could help me resolve it.

I've been able to locate the spades_func.py file, however I cannot locate where I should type "--tmp-dir /tmp" into the file.

Could you (or possibly @rrwick ) show me where to enter that fix into the script?

Best,
Curtis

**Comment by rec3141** [comment]
@kapsakcj Hi Curtis, I've attached a [patch](https://github.com/rrwick/Unicycler/files/1661992/patch.txt), and the changes are shown below


line 251
old: `command += ['-o', read_correction_dir, '--threads', str(threads), '--only-error-correction']`
new: `command += ['-o', read_correction_dir, '--threads', str(threads), '--only-error-correction', '--tmp-dir', '/tmp']`

line 345
old: `command = [spades_path, '-o', out_dir, '-k', kmer_string, '--threads', str(threads)]`
new: `command = [spades_path, '-o', out_dir, '-k', kmer_string, '--threads', str(threads), '--tmp-dir', '/tmp']`

**Comment by kapsakcj** [comment]
Wow, thank you for the fast response, I will test this out as soon as I can.

One more question, will I need to move my data to the /tmp directory w/in my virtualbox (and subsequently alter my unicycler command) in order for this to work? Or can I leave the data in the vboxsf folders that they currently reside in?

Thanks!

**Comment by kapsakcj** [comment]
This did in fact fix the error with SPAdes. Unicycler worked like a charm afterwards and generated an assembly. Thanks a lot! @rec3141

**Comment by rec3141** [comment]
You can leave them where they are, this is just for where spades writes its
own tmp files

**Comment by rrwick** [comment]
Thanks for the help @rec3141!

**Comment by rrwick** [comment]
Oops - I just closed the issue, but I think I'll leave it open as an enhancement request. I'll close it when I add some Unicycler options to make this easier.

**Comment by rrwick** [comment]
Okay, I've added a `--spades_tmp_dir` option in this commit: https://github.com/rrwick/Unicycler/commit/0ea7b98b5706f910c4ebb1f3fda1886f10315c82

I've also added a note in the [Unicycler FAQs](https://github.com/rrwick/Unicycler/wiki/FAQs).

The change is currently just in the development branch, but it should make it into the next release. Thanks again!

**Comment by rrwick** [comment]
In case anyone still runs into this issue, I thought I'd mention that in the upcoming version of Unicycler (v0.5.0), I've removed the `--spades_tmp_dir` option because there is now the more general `--spades_options` which lets you pass any option to SPAdes.

So instead of `--spades_tmp_dir path/to/dir` you can use `--spades_options "--tmp-dir path/to/dir"`
