### ISSUE TITLE
upgrading unicycler

### ISSUE THREAD

**Issue by supanthee** [rrwick/Unicycler#71]
Hi Ryan,

Maybe very trivial issue but I can not install the current version of unicycler using git clone https://github.com/rrwick/Unicycler.git. It says folder already exists. Perhaps I need to uninstall the current version. How do I proceed?

Thanks

**Comment by supanthee** [comment]
I tried pip3 install git+https://github.com/rrwick/Unicycler.git and now it shows 0.4.3.

Thanks

**Comment by rrwick** [comment]
Glad you got it working! In the future you can also delete the existing directory before cloning again - that should avoid the git error.

Ryan
