### ISSUE TITLE
TypeError: end must be None or a string, not int

### ISSUE THREAD

**Issue by phbrito** [rrwick/Unicycler#72]
Hello,
I am using Unicycler to perform an hybrid assembly of a bacterial genome using illumina and Nanopore (Albacore v. 2.1.3) reads. Unfortunately, the program aborts with an error message

I am using Unicycler v0.4.1, installed with miniconda
Illumina reads were previously adapter trimmed using trimmomatic  - and I’m using as input data just the 1P and 2P output files from trimmomatic that have the paired reads.
Nanopore reads were previously adapter trimmed using Porechop 

This is my command line:
unicycler -1 B-0001-16_S4_L001_trimed_1P.fastq -2 B-0001-16_S4_L001_trimed_2P.fastq -l albacore_1D.porechop.fastq -o unicycler_normal_1illumina --verbosity 2 --keep 2 -t 8 --mode normal --contamination lambda

I get the following outputs:
001_best_spades_graph.gfa
002_overlaps_removed.gfa
003_long_read_assembly.gfa
unicycler.log

Last on screen output with error message:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/unicyc/bin/unicycler", line 11, in <module>
    load_entry_point('unicycler==0.4.1', 'console_scripts', 'unicycler')()
  File "/home/ubuntu/miniconda3/envs/unicyc/lib/python3.5/site-packages/unicycler/unicycler.py", line 167, in main
    read_dict, read_names, long_read_filename)
  File "/home/ubuntu/miniconda3/envs/unicyc/lib/python3.5/site-packages/unicycler/unicycler.py", line 989, in align_long_reads_to_assembly_graph
    log.log('\nDiscarded', contaminant_read_count, 'reads as contamination', 2)
  File "/home/ubuntu/miniconda3/envs/unicyc/lib/python3.5/site-packages/unicycler/log.py", line 75, in log
    print(text, file=sys.stderr, end=end, flush=True)
TypeError: end must be None or a string, not int

Last line on log file:
Deleting /unicycler/unicycler_normal_1illumina/read_alignment/

Hopping you can shed some light on this.
Thanks very much!
Patrícia

**Comment by phbrito** [comment]
Just to let you know that if I do not include the command "--contamination lambda" the program runs finely until the end.
Patrícia

**Comment by rrwick** [comment]
Thanks for the bug report! I spotted the issue and fixed it in this commit: 7e6756a37947c3b3660bbc233bde278e71c2c902

This fix is only in the development branch at the moment, so to use it you'll need to follow the [Install from source](https://github.com/rrwick/Unicycler#install-from-source) steps, but replace `git clone https://github.com/rrwick/Unicycler.git` with `git clone -b development https://github.com/rrwick/Unicycler.git`

The fix will be in the next bug-fix release of Unicycler (v0.4.4). Thanks again!

Ryan
