### ISSUE TITLE
Issue installing Unicycler

### ISSUE THREAD

**Issue by rackingmyhead** [rrwick/Unicycler#73]
I am having an issue this time installing Unicycler. Had it working in CentOS 6 but this time we are using CentOS 7. When I run the setup.ph script I am getting the following error:

running install
Cleaning previous compilation: make distclean
Platform: Linux
Compiler: g++ 4.8.5
Makefile:54: *** Unicycler requires GCC version 4.9.1 or greater.  Stop.
Compiling Unicycler: make -j 8
Platform: Linux
Compiler: g++ 4.8.5
Makefile:54: *** Unicycler requires GCC version 4.9.1 or greater.  Stop.
Error: compilation of Unicycler's C++ component failed

**When I run gcc --version I get:**

gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**And when I run cc --version I get:**

cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by ncimb** [comment]
Looks like theres a fix in the pending pull request #74  - probably can just change the makefile if you need a quick fix - I hit this one too.

**Comment by rrwick** [comment]
Thanks for the heads up! I've merged that pull request into the development branch, so you can try it by following the [Install from source](https://github.com/rrwick/Unicycler#install-from-source) steps, but replace `git clone https://github.com/rrwick/Unicycler.git` with `git clone -b development https://github.com/rrwick/Unicycler.git`

The next bug fix release (v0.4.4) isn't too far away, and that will contain the fix as well. I'm going to close this issue now, but please let me know if the fix doesn't work or if you have any other build issues!

Ryan

**Comment by rackingmyhead** [comment]
Thanks Ryan I will give it a shot. I was able to get it installed a few
weeks ago after posting but it would not run properly.

**Comment by rrwick** [comment]
Okay, if you still have issues making it run, can you create a new issue with the details? Thanks!

**Comment by Xiaojun928** [comment]
Hi, wick

I am also having an issue when installing Unicycler. I am working on CenOS7 with gcc 7.3.0. 
and using `git clone -b development https://github.com/rrwick/Unicycler.git`
I got this error when run the setup.py script:

running install
Cleaning previous compilation: make distclean
Platform: Linux
Compiler: g++ 7.3.0
rm -f unicycler/src/overlap_align.o unicycler/src/miniasm_assembly.o unicycler/src/semi_global_align_exhaustive.o unicycler/src/start_end_align.o unicycler/src/minimap_align.o unicycler/src/path_align.o unicycler/src/global_align.o unicycler/src/minimap/kthread.o unicycler/src/minimap/sketch.o unicycler/src/minimap/map.o unicycler/src/minimap/sdust.o unicycler/src/minimap/bseq.o unicycler/src/minimap/index.o unicycler/src/minimap/misc.o unicycler/src/ref_seqs.o unicycler/src/miniasm/hit.o unicycler/src/miniasm/sys.o unicycler/src/miniasm/asg.o unicycler/src/miniasm/paf.o unicycler/src/miniasm/sdict.o unicycler/src/miniasm/asm.o unicycler/src/miniasm/dotter.o unicycler/src/random_alignments.o unicycler/src/semi_global_align.o unicycler/src/consensus_align.o unicycler/src/scoredalignment.o unicycler/src/string_functions.o unicycler/src/kmers.o unicycler/src/scrub.o
rm -f unicycler/cpp_functions.so
Compiling Unicycler: make -j 8
Platform: Linux
Compiler: g++ 7.3.0
g++ -std=c++14 -Iunicycler/include -fPIC -lrt -lpthread -O3 -DNDEBUG -Wall -Wextra -pedantic -mtune=native -c -o unicycler/src/overlap_align.o unicycler/src/overlap_align.cpp
g++ -std=c++14 -Iunicycler/include -fPIC -lrt -lpthread -O3 -DNDEBUG -Wall -Wextra -pedantic -mtune=native -c -o unicycler/src/miniasm_assembly.o unicycler/src/miniasm_assembly.cpp
g++ -std=c++14 -Iunicycler/include -fPIC -lrt -lpthread -O3 -DNDEBUG -Wall -Wextra -pedantic -mtune=native -c -o unicycler/src/semi_global_align_exhaustive.o unicycler/src/semi_global_align_exhaustive.cpp
g++ -std=c++14 -Iunicycler/include -fPIC -lrt -lpthread -O3 -DNDEBUG -Wall -Wextra -pedantic -mtune=native -c -o unicycler/src/start_end_align.o unicycler/src/start_end_align.cpp
g++ -std=c++14 -Iunicycler/include -fPIC -lrt -lpthread -O3 -DNDEBUG -Wall -Wextra -pedantic -mtune=native -c -o unicycler/src/minimap_align.o unicycler/src/minimap_align.cpp
g++ -std=c++14 -Iunicycler/include -fPIC -lrt -lpthread -O3 -DNDEBUG -Wall -Wextra -pedantic -mtune=native -c -o unicycler/src/path_align.o unicycler/src/path_align.cpp
g++ -std=c++14 -Iunicycler/include -fPIC -lrt -lpthread -O3 -DNDEBUG -Wall -Wextra -pedantic -mtune=native -c -o unicycler/src/global_align.o unicycler/src/global_align.cpp
g++ -std=c++14 -Iunicycler/include -fPIC -lrt -lpthread -O3 -DNDEBUG -Wall -Wextra -pedantic -mtune=native -c -o unicycler/src/minimap/kthread.o unicycler/src/minimap/kthread.cpp
unicycler/src/minimap_align.cpp:15:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make: *** [Makefile:118: unicycler/src/minimap_align.o] Error 1
make: *** Waiting for unfinished jobs....
Error: compilation of Unicycler's C++ component failed


But I have successfully install zlib and /usr/local/include contains zconf.h   zlib.h  zutil.h 

Could you please give me some help? Thanks a lot!
