### ISSUE TITLE
Fail dependency - java 9.0.1 too old

### ISSUE THREAD

**Issue by maculatus** [rrwick/Unicycler#75]
Hello, I have a linux 16.04 ubuntu and I re-installed the last unicycler version. The installation was suceesfull. However when I tried my first run the dependency program failed with Java 9.0.1 "too old".
What is the version that Unicycler is using? Is this a way to correct this?

**Comment by maculatus** [comment]
Today I was able to run the program again. This time the dependency Java 9.0.1 was "good". I am going to look for "Gremlins"

**Comment by rrwick** [comment]
I'm glad you got it working, but the gremlins are indeed odd. There was a known bug with Java version parsing, but that was fixed in the latest version of Unicycler (0.4.3). Let me know if you encounter the problem again!

Ryan
