### ISSUE TITLE
some advice for unmet deps?

### ISSUE THREAD

**Issue by rafalcode** [rrwick/Unicycler#76]
As Unicycler has a number of dependencies I was wondering if some extra advice on what to do when they are unmet can be given?

i.e. I get 
Dependencies:
  Program         Version    Status 
  spades.py       3.10.0     good    
  racon                      not used
  makeblastdb     2.2.30+    good   
  tblastn         2.2.30+    good    
  bowtie2-build   2.1.0      good   
  bowtie2         2.1.0      good    
  samtools        1.3.1      good   
  java            1.6.0_45   too old
  pilon           1.22       good    
  bcftools                   not used

In a system using environment modules, a special java is loaded ... i.e. java8 for example is in a non-standard location, but the standard java6 is being found instead. Unusually however, many of the other dependencies are being found. I tried to find out in the code how exactly java is being searched for, but no luck (as least, yet). Actually this is a difficult issue ... autoconf also has a tortuous way of looking for dependencies.

**Comment by rrwick** [comment]
Unicycler uses Python's `shutil.which` function, which is (I think) equivalent to running `which java` on the command line. So if there are multiple java executables on your system, I think it will find whichever is first in your PATH variable.

Two immediate solutions jump to mind:

1. Manually add the path to the java you want to use to your PATH before running Unicycler:<br> `export PATH=/path/to/newer/java/dir/:"$PATH"`
2. Specify the java executable in Unicycler's command:<br> `--java_path /path/to/newer/java/dir/java`

A final option would be to call Unicycler with `--no_pilon` which turns off Pilon polishing and removes the Java dependency. That will also make Unicycler run faster, but may not be ideal if you're hoping for as-polished-as-possible assemblies.

Let me know how you go!
Ryan

**Comment by rafalcode** [comment]
Thanks Ryan, that tells me what I need to know.
I'll focus on shutil.which and see why it isn't getting the right java.
Cheers!

**Comment by rrwick** [comment]
Okay, I'll close this issue now, but please reopen it if you still have issues or feel that Unicycler isn't working properly.

Ryan
