### ISSUE TITLE
Pilon still not being auto-detected

### ISSUE THREAD

**Issue by tseemann** [rrwick/Unicycler#8]
We are using the current HEAD 0.3.0b version. 

We have `pilon` in the PATH which is a bash wrapper for the JAR.

But it still says "unable to find pilon" at the end of a unicycler run.

Is it only in dev branch?

**Comment by rrwick** [comment]
:grimacing: Sorry about that - I've spotted the problem and actually fixed it up this time (I think). I'm reasonably confident that the development branch wasn't broken, so I've merged all of its changes (including this one) to the master branch. So if you pull from master and try again, I think it will work!
