### ISSUE TITLE
unicycler on eukaryote genome

### ISSUE THREAD

**Issue by DelphIONe** [rrwick/Unicycler#81]
I have forgotten this specificity of unicycler mentionned on site "only for bacteria" and I have launched it on a fungi genome. The total size is the expected size so, why I will not be able to use this result from Unicycler ? Why Unicycler couldn't work fine on an eukaryote genome? Is it a ploidie problem ?

Thanks for your reply,
Delphine

**Comment by rrwick** [comment]
Hi Delphine,

Glad to hear it worked!

The short version is that I designed Unicycler for and tested it on bacterial isolates only.

More specifically, I would be concerned about:
* Ploidy: a diploid genome might really throw off some of Unicycler's logic, depending on how much heterogeneity there is.
* Linear replicons: Unicycler was mainly built for circular replicons, and it might cut the ends off linear replicons too much (also a problem for linear chromosomes/plasmids in bacteria - improving this is on my to do list).
* Performance: some of Unicycler's algorithms are fine for a 5 Mbp genome but might take _ages_ on a 1 Gbp genome.
* Repeat content: Unicycler assumes that most of the assembly is not a repeat - a pretty safe assumption for bacteria but not true for a lot of big eukaryote genomes.

So, if your fungus has a smallish, simple, haploid genome, Unicycler will likely do just fine! But do double-check the ends of chromosomes which may be missing. If your fungus genome is big, repeat-rich and/or diploid, then I suspect some other assembly tool might do a better job.

Hope that helps! I'll close this issue now, but feel free to keep asking questions if anything's not clear.

Ryan

**Comment by DelphIONe** [comment]
Thanks for your reply Ryan!
I've forgotten to say, I obtain 62 contigs with Unicycler (the best_spades_graph.gfa file is close to C figure in your doc (a disaster) ) and 48 with Canu. Do you know any tips to try improve this (I expected only 7 contigs (=chromosome). In an ideal world but I can dream :-)

Delphine

**Comment by rrwick** [comment]
It's tough to say without more information, but if you want a truly _completed_ genome (i.e. one contig per chromosome), then you are going to need a lot of very long reads! Are you using Nanopore? If so, look into Josh Quick and Nick Loman's ultra long read protocols. But even with ultra long reads, one contig per chromosome is a tall order! Some genomic regions, like centromeres, can be very hard to assemble. Two contigs per chromosome (one for each arm) might be a more realistic goal.

Ryan

**Comment by DelphIONe** [comment]
Yes, I have too Nanopore reads. Thanks for your advices.

**Comment by supanthee** [comment]
Hi, I tried to assemble Ion PGM and nanopore reads with --no_correct option for fungi and it appears to me that it worked fine. The number of contigs I received is 331 for hybrid assembly and 25 for long reads only assembly. Is it because it uses SPAdes and does not discard the smaller contigs? When I mapped the contigs back to the PGM reads, I found that 99.35% of bases were mapped (table below). Do you think I can consider this as a good assembly or I should think of other options?

Waiting for your comments.

Suresh

![screen shot 2018-03-30 at 16 27 48](https://user-images.githubusercontent.com/28749615/38128855-5dceb7ee-3437-11e8-9c42-c5bb42e3aa38.png)

**Comment by Aurelie-Quade** [comment]
Hi Ryan, 

I have used Unicycler on Puccinia genome, which is large 1Gbp and has lot of repeat regions and is diploid. It worked, but how do I assess the quality of the assembly. 

I have assembled 16 short read Illumina, De novo of Puccinia sorghi on Unicycler. 

Thank you for your help, 
Best Regards,
Aurelie
