### ISSUE TITLE
Error: SPAdes crashed during read correction

### ISSUE THREAD

**Issue by kapsakcj** [rrwick/Unicycler#82]
Hi,
I ran into an issue while running Unicycler for the first time. I'm trying out a hybrid assembly using paired-end Illumina reads and MinION reads. I was wondering if anyone can help me get Unicycler running.

It appears that SPAdes crashed during the read error correction step and I was directed to the spades.log for information. I found the following:
```
=== Stack Trace ===
[0x408b5e]
[0x409a91]
[0x40d61b]
[0x4012fa]
[0x541e60]
[0x40668d]
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'void MMappedWriter::reserve(size_t)'. In file '/spades/src/common/io/kmers/mmapped_writer.hpp' on line 92. Message 'mmap(2) failed. Reason: Invalid argument. Error code: 22'.
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'void MMappedWriter::reserve(size_t)'. In file '/spades/src/common/io/kmers/mmapped_writer.hpp' on line 92. Message 'mmap(2) failed. Reason: Invalid argument. Error code: 22'.
hammer: /spades/src/common/io/kmers/mmapped_writer.hpp:92: void MMappedWriter::reserve(size_t): Assertion `(intptr_t) MappedRegion != -1L' failed.


== Error ==  system call for: "['/home/curtis/miniconda2/envs/unicyclerEnv/share/spades-3.10.1-0/bin/hammer', '/media/sf_sharedVMfolder/unicyclerTestrun/spades_assembly/read_correction/corrected/configs/config.info']" finished abnormally, err code: -6
```

After some googling, I think this may have to do with the fact that I'm running Unicycler on VirtualBox with Ubuntu 14.04. And my sequence files are located in a shared folder that I have setup between my host OS (windows) with the guest OS (Ubuntu 14.04). Does this have anything to do with it?

Best,
Curtis

**Comment by rec3141** [comment]
see https://github.com/rrwick/Unicycler/issues/69#issuecomment-360305189

**Comment by rrwick** [comment]
@rec3141, I saw your patch in issue #69. Did that fix the problem? I have noticed a similar problem: that SPAdes doesn't work over mounted network drives. I'll try your solution, and if it works, I may make a new Unicycler option `--spades_tmp_dir` so people don't have to hack the Unicycler code.

Thanks!
Ryan

**Comment by rrwick** [comment]
Since a couple people have now hit this problem, I may make a new Unicycler option `--spades_tmp_dir` so people don't have to hack the Unicycler code. It should be an easy addition that I can put into the next release.

Ryan

**Comment by kapsakcj** [comment]
The fix [https://github.com/rrwick/Unicycler/issues/69#issuecomment-360305189](url) did in fact work for me. SPAdes read error correction ran fine I edited the python script. I think it would be a good little fix for the next release

**Comment by rec3141** [comment]
Hey Ryan, yes that would be great, and you might want to put a note in the docs on why that option is there (virtual box) and to note that it should be a vbox local directory

**Comment by rrwick** [comment]
See issue #69: the `--spades_tmp_dir` option is now in the development branch and will be in the next release.
