### ISSUE TITLE
Miniasm Empty Result

### ISSUE THREAD

**Issue by conra91** [rrwick/Unicycler#83]
Hi Ryan,

Similar issue to the one presented here:
https://github.com/rrwick/Unicycler/issues/38

I believe I do have quite low coverage but it is bacterial genome with, I would have thought, enough bases for the assembly. (Reads: 65, 588. 114, 533, 858 bp). At this stage I only have long read data so can't perform a hybrid unicycler assembly. Any thoughts/tips?

Connor

````
Loading reads (2018-01-25 09:43:35)
65,588 / 65,588 (100.0%) - 114,533,858 bp

Duplicate read names found. Saving duplicate-free file:
.../assemblies/1/1_no_duplicates.fastq.gz


Assembling contigs and long reads with miniasm (2018-01-25 09:44:37)
Saving to .../assemblies/1/miniasm_assembly/01_assembly_reads.fastq:
  65,588 long reads

Finding overlaps with minimap... success
  681,609 overlaps

Assembling reads with miniasm... empty result

 ===============================================================================
 Job finished at Thu Jan 25 09:44:53 GMT 2018
```

**Comment by rrwick** [comment]
How big is your genome? For a large bacterial genome (6 Mbp or so), this is under 20x depth, which is kind of on the fence for miniasm success. You could try Canu instead. The [FAQ here](http://canu.readthedocs.io/en/latest/faq.html#my-assembly-continuity-is-not-good-how-can-i-improve-it) has some suggestions for lower depth read sets.

If it's a small genome, however, then you should have enough depth, but read length may still be an issue. Your mean read length is about 1750 kbp, which isn't great. Are these Nanopore reads? PacBio?

Ryan

**Comment by conra91** [comment]
Yeah it was about 6Mbp with Nanopore reads. Managed to get Canu to work, but yeah - I think poor coverage and not fantastic read length (probably due to dodgy sample prep) contributed. No problem - I'll close this now.
