### ISSUE TITLE
Error during pilon polish

### ISSUE THREAD

**Issue by sulheim** [rrwick/Unicycler#84]
I tried to run Unicycler on a Virtual Box with Ubuntu 16.04, but it crashed during Pilon polish. Any idea what went wrong? Is it possible to continue the assembly, and only do the polishing?

`
Traceback (most recent call last):
  File "/usr/local/bin/unicycler", line 9, in <module>
    load_entry_point('unicycler==0.4.3', 'console_scripts', 'unicycler')()
  File "/usr/local/lib/python3.5/dist-packages/unicycler/unicycler.py", line 212, in main
    final_polish(graph, args, counter, long_reads_available)
  File "/usr/local/lib/python3.5/dist-packages/unicycler/unicycler.py", line 925, in final_polish
    polish_with_pilon_multiple_rounds(graph, graph, args, polish_dir, do_pilon_reassembly)
  File "/usr/local/lib/python3.5/dist-packages/unicycler/pilon_func.py", line 64, in polish_with_pilon_multiple_rounds
    insert_size_99th, i+1, fix_type)
  File "/usr/local/lib/python3.5/dist-packages/unicycler/pilon_func.py", line 335, in polish_with_pilon
    os.remove(f)
OSError: [Errno 26] Text file busy: '1_pilon.changes'
`

**Comment by kapsakcj** [comment]
I too just ran into what I believe is the same issue you experienced. I believe it has to do with the fact that you're running it through VirtualBox. Check out this fix here, as it worked for me: https://github.com/rrwick/Unicycler/issues/69#issuecomment-360305189

**Comment by sulheim** [comment]
@kapsakcj sure? I encountered the Spades-issue as well,  and changed the first line there, and that fixed the Spades-thing, but I thiink this is related to Pilon...

**Comment by kapsakcj** [comment]
@sulheim I apologize, I was confusing the two issues with one another. I too had both issues pop up when running Unicycler through VirtualBox.

The SPAdes fix worked for me, but I have not been able to figure out what is causing the issue with Pilon. So I too am looking for a solution!

**Comment by kapsakcj** [comment]
@sulheim I see from your original post that you are using unicycler v0.4.3. You may want to update to the current release (v0.4.4) and try running it again. I ran the current release of unicycler and did not see an error message during the pilon step as I saw before. YMMV

**Comment by sulheim** [comment]
Got the same error with Unicycler v0.4.4

**Comment by apredeus** [comment]
I didn't get the same error with 0.4.5, but Pilon was failing with "not enough memory" error when I ran it on 8-16 threads. You can go to pilon wrapper and change Java memory limit (Xmx) to 20 G or something else, depending on what your setup allows. 

It might have nothing to do with memory though, it's hard to tell, since the error message you get is very uninformative.

**Comment by rrwick** [comment]
Hi @sulheim,

I don't really understand why this crash happened (or why it stopped happening in v0.4.5) but I've added an extra bit to catch the error, hopefully preventing such crashes in the future: 078a782. This is only in Unicycler's development branch now, but should make its way into the next release.

Regarding the memory issue and the wrapper suggestion @apredeus mentioned, you can find more info here: #63.

Hope that helps!
Ryan
