### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by martingui** [rrwick/Unicycler#89]
Hi,
I have tried installing unicycler in two different ways and neither worked.
I tried the 'build and run without installation' and when checking the dependencies, racon appears as 'bad' even though I used the latest version, I tried entering the path directly with '--racon_path ~/bin/racon/build/bin/racon' but the output is
'Racon was found but does not produce output'

So I tried the 'install from source' way.
when running 'unicycler' i get the following message:

Traceback (most recent call last):
  File "/home/t03mg18/bin/unicyclert/bin/unicycler", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'unicycler==0.4.4' distribution was not found and is required by the application

I don't have sudo privileges so I installed in my own folders and not the /usr/bin so maybe that is the problem?
I hope you can help me

Martin.

**Comment by martingui** [comment]
I managed to make the first way ('build and run without installation') work. The problem seems to be that the new version of Racon (1.00) is not supported anymore by unicycler, as the program works when I tried installing Racon's previous version (0.5).
Martin

**Comment by kapsakcj** [comment]
Somewhat related to your issue (sorry I can't offer a solution for you!) - The new release of Racon (1.0) has caused some problems for me with the Bioconda implementation of Unicycler too. I'm not sure if @rrwick handles the Unicycler Bioconda repository or if others do...but here's what happened to me:

I installed the latest version of Unicycler via conda
`conda install unicycler racon=0.5`
Tested Racon installation with:
`racon --help`

And I got the following error back:
`Illegal instruction (core dumped)`

[https://twitter.com/CurtisKapsak/status/966812033646759936](https://twitter.com/CurtisKapsak/status/966812033646759936)

Thanks to @druvus 's fix (thank you!), the bioconda route of installing Racon 1.0 works (no error message!), but when I install Racon 0.5 using conda, I get the error message shown above when I run `racon --help`

Curtis

**Comment by rrwick** [comment]
No, I'm afraid I don't control the Unicycler Bioconda repo. Anyway, the latest release of Unicycler (v0.4.6) now supports current versions of Racon, so I hope that solves the problem! I'm going to optimistically close this issue, but if you're still having problems, go ahead and reopen it.

Ryan
