### ISSUE TITLE
 Problem encoding the character '\u2190'

### ISSUE THREAD

**Issue by arredondo23** [rrwick/Unicycler#9]
Hi Ryan,

We had some troubles in our HPC with the character '\u2190' which draws an arrow in the output given by the program. It raised the following error:
**UnicodeEncodeError: 'ascii' codec can't encode character '\u2190' in position 48: ordinal not in range(128)**

We solved the problem just replacing the character by a semicolon in the libraries. We are not sure if there is a more generic solution. 

Thanks for this amazing software,

Sergio.

**Comment by rrwick** [comment]
I suspect that I've already fixed this one in https://github.com/rrwick/Unicycler/commit/c97159770522fb42fc749998350a81698870f273. In that change I made Unicycler see if the system could handle the`←` and ` →`characters, and if not it uses `<-` and `->` instead.

So if you clone/install from the master branch on GitHub, you'll get this fix (and a handful of other ones as well). Alternatively, wait for Unicycler v0.3.0, which shouldn't be too far off and will include the fix.

I'll assume that you're running a pre-fix version of Unicycler (e.g. the v0.2.0 release) and close this issue. If, however, you're running a current version (i.e. https://github.com/rrwick/Unicycler/commit/c97159770522fb42fc749998350a81698870f273 failed to fix it) then let me know - I'll reopen it and investigate further!

**Comment by arredondo23** [comment]
Thanks for the answer! We downloaded Unicycler using conda, and indeed the version we were running was the v0.2.0.

**Comment by druvus** [comment]
@arredondo23 I have bumped  bioconda's unicycler version to latest commit (listed as v0.3.0b). Please check it works for you now.

**Comment by arredondo23** [comment]
Great! Yes, the new version of Unicycler has been updated to v0.3.0b calling bioconda again. Thanks for the help @rrwick @druvus
