### ISSUE TITLE
Performance of Unicycler 0.4.4 with Racon v1.1.0

### ISSUE THREAD

**Issue by a1204350** [rrwick/Unicycler#91]
Hi there,

I recently upgraded Racon used in Unicycler from v0.5 to v1.1 and found that Unicycler completed the genome using version 0.5, but when using v1.1 on the exactly same genome, it left an incomplete plasmid behind.

Both runs used exactly same reads from Illumina and MinION, but with different outcome. So I'm just wondering which one I should trust on. Should I donwgrade Racon to v0.5 in Unicycler?

I also noticed that in the log file

When using Unicycler with Racon v0.5

Unicycler now places the single copy contigs back into the unitig graph. This serves two purposes: a) it replaces long read assembly sequences (which may be error prone) with Illumina assembly sequence (which is probably quite accurate), improving the assembly quality, and b) it defines inter-contig sequences for use in building bridges.

Searching for contigs using 5,000 bp of contig ends.

Contig   Result              Start pos   End pos   Strand
     1   found in unitig 1     4794607   5189811        -
     2   found in unitig 1     1248644   1615044        -
     3   found in unitig 1     3326835   3679829        -
     4   found in unitig 1     2365498   2704086        -
     5   found in unitig 1     2024615   2340658        -
     6   found in unitig 1     4326583   4593570        +
     7   found in unitig 1     3898508   4161591        -
     8   found in unitig 1      -97149    122448        -
     9   found in unitig 1      154578    357949        -
    10   found in unitig 1     3687247   3890653        +
    11   found in unitig 1     3139886   3325183        -
    12   found in unitig 1     1683099   1858699        -
    13   found in unitig 1     1008496   1178481        -
    14   found in unitig 1     2810592   2980272        +
    15   found in unitig 1     2996810   3139302        +
    16   found in unitig 1      878013   1007062        -
    17   found in unitig 1     4195549   4297554        +
    18   found in unitig 1     4624690   4724475        +
    19   found in unitig 1      636924    736035        -
    20   found in unitig 1      359410    452973        -
    21   found in unitig 1     1859892   1952608        +
    22   found in unitig 1      741267    827561        -
    23   found in unitig 1     2705986   2775605        -
    24   found in unitig 1      571050    631581        +
    25   found in unitig 1     5293812   5353535        -
    26   found in unitig 1     1952815   2011207        -
    27   found in unitig 1     1620410   1677703        +
    28   found in unitig 1     4729749   4784634        +
    29   found in unitig 1      454172    505814        -
    30   found in unitig 1     5191000   5242065        +
    31   found in unitig 1      531124    568658        +
    32   found in unitig 1     5256221   5293046        +
    33   found in unitig 2        1010     35801        +
    34   found in unitig 1      838446    872661        +
    35   found in unitig 1     2777508   2809121        -
    36   found in unitig 1     4299011   4325155        -
    37   found in unitig 1      127579    153569        +
    38   found in unitig 1     4597823   4622782        +
    39   found in unitig 1     1223305   1243264        +
    40   found in unitig 1     1180252   1200211        -
    41   found in unitig 1      510299    529958        -
    42   found in unitig 2       38816     57831        -
    43   found in unitig 1     4167938   4186259        +
    44   found in unitig 2       89772    105089        -
    45   found in unitig 2      137029    150672        +
    46   found in unitig 1     2981472   2994872        +
    47   found in unitig 1     1209430   1222138        -
    48   found in unitig 1     2351661   2364310        -
    49   found in unitig 1     5243256   5255457        +
    50   found in unitig 1     2012662   2024408        +
    52   found in unitig 2       66953     76603        +
    53   found in unitig 2      111342    120268        +
    54   found in unitig 2       80372     87899        -
    55   found in unitig 1     4187025   4194342        -
    56   found in unitig 1     2342567   2349754        -
    57   found in unitig 1     4786544   4793412        +
    58   found in unitig 1     3681020   3687000        -
    60   found in unitig 2       61293     66351        -
    61   found in unitig 2       -4449       429        -
    62   found in unitig 1      832998    837435        -
    63   found in unitig 1     1205687   1209281        +
    64   found in unitig 1     1677852   1681436        -
    65   found in unitig 1      506023    509484        -
    66   found in unitig 2      107483    110524        +

Saving /home/zong/Desktop/3/1/095649bb_Mde_hybrid_conservative/miniasm_assembly/15_contigs_placed.gfa

When using Unicycler with Racon v1.1

Unicycler now places the single copy contigs back into the unitig graph. This serves two purposes: a) it replaces long read assembly sequences (which may be error prone) with Illumina assembly sequence (which is probably quite accurate), improving the assembly quality, and b) it defines inter-contig sequences for use in building bridges.

Searching for contigs using 5,000 bp of contig ends.

Contig   Result      Start pos   End pos   Strand
     1   not found                               
     2   not found                               
     3   not found                               
     4   not found                               
     5   not found                               
     6   not found                               
     7   not found                               
     8   not found                               
     9   not found                               
    10   not found                               
    11   not found                               
    12   not found                               
    13   not found                               
    14   not found                               
    15   not found                               
    16   not found                               
    17   not found                               
    18   not found                               
    19   not found                               
    20   not found                               
    21   not found                               
    22   not found                               
    23   not found                               
    24   not found                               
    25   not found                               
    26   not found                               
    27   not found                               
    28   not found                               
    29   not found                               
    30   not found                               
    31   not found                               
    32   not found                               
    33   not found                               
    34   not found                               
    35   not found                               
    36   not found                               
    37   not found                               
    38   not found                               
    39   not found                               
    40   not found                               
    41   not found                               
    42   not found                               
    43   not found                               
    44   not found                               
    45   not found                               
    46   not found                               
    47   not found                               
    48   not found                               
    49   not found                               
    50   not found                               
    52   not found                               
    53   not found                               
    54   not found                               
    55   not found                               
    56   not found                               
    57   not found                               
    58   not found                               
    60   not found                               
    61   not found                               
    62   not found                               
    63   not found                               
    64   not found                               
    65   not found                               
    66   not found                               

Searching for contigs using 2,500 bp of contig ends.

Contig   Result      Start pos   End pos   Strand
     1   not found                               
     2   not found                               
     3   not found                               
     4   not found                               
     5   not found                               
     6   not found                               
     7   not found                               
     8   not found                               
     9   not found                               
    10   not found                               
    11   not found                               
    12   not found                               
    13   not found                               
    14   not found                               
    15   not found                               
    16   not found                               
    17   not found                               
    18   not found                               
    19   not found                               
    20   not found                               
    21   not found                               
    22   not found                               
    23   not found                               
    24   not found                               
    25   not found                               
    26   not found                               
    27   not found                               
    28   not found                               
    29   not found                               
    30   not found                               
    31   not found                               
    32   not found                               
    33   not found                               
    34   not found                               
    35   not found                               
    36   not found                               
    37   not found                               
    38   not found                               
    39   not found                               
    40   not found                               
    41   not found                               
    42   not found                               
    43   not found                               
    44   not found                               
    45   not found                               
    46   not found                               
    47   not found                               
    48   not found                               
    49   not found                               
    50   not found                               
    52   not found                               
    53   not found                               
    54   not found                               
    55   not found                               
    56   not found                               
    57   not found                               
    58   not found                               
    60   not found                               
    61   not found                               
    62   not found                               
    63   not found                               
    64   not found                               
    65   not found                               
    66   not found                               

Searching for contigs using 1,000 bp of contig ends.

Contig   Result      Start pos   End pos   Strand
     1   not found                               
     2   not found                               
     3   not found                               
     4   not found                               
     5   not found                               
     6   not found                               
     7   not found                               
     8   not found                               
     9   not found                               
    10   not found                               
    11   not found                               
    12   not found                               
    13   not found                               
    14   not found                               
    15   not found                               
    16   not found                               
    17   not found                               
    18   not found                               
    19   not found                               
    20   not found                               
    21   not found                               
    22   not found                               
    23   not found                               
    24   not found                               
    25   not found                               
    26   not found                               
    27   not found                               
    28   not found                               
    29   not found                               
    30   not found                               
    31   not found                               
    32   not found                               
    33   not found                               
    34   not found                               
    35   not found                               
    36   not found                               
    37   not found                               
    38   not found                               
    39   not found                               
    40   not found                               
    41   not found                               
    42   not found                               
    43   not found                               
    44   not found                               
    45   not found                               
    46   not found                               
    47   not found                               
    48   not found                               
    49   not found                               
    50   not found                               
    52   not found                               
    53   not found                               
    54   not found                               
    55   not found                               
    56   not found                               
    57   not found                               
    58   not found                               
    60   not found                               
    61   not found                               
    62   not found                               
    63   not found                               
    64   not found                               
    65   not found                               
    66   not found                               

Searching for contigs using 500 bp of contig ends.

Contig   Result      Start pos   End pos   Strand
     1   not found                               
     2   not found                               
     3   not found                               
     4   not found                               
     5   not found                               
     6   not found                               
     7   not found                               
     8   not found                               
     9   not found                               
    10   not found                               
    11   not found                               
    12   not found                               
    13   not found                               
    14   not found                               
    15   not found                               
    16   not found                               
    17   not found                               
    18   not found                               
    19   not found                               
    20   not found                               
    21   not found                               
    22   not found                               
    23   not found                               
    24   not found                               
    25   not found                               
    26   not found                               
    27   not found                               
    28   not found                               
    29   not found                               
    30   not found                               
    31   not found                               
    32   not found                               
    33   not found                               
    34   not found                               
    35   not found                               
    36   not found                               
    37   not found                               
    38   not found                               
    39   not found                               
    40   not found                               
    41   not found                               
    42   not found                               
    43   not found                               
    44   not found                               
    45   not found                               
    46   not found                               
    47   not found                               
    48   not found                               
    49   not found                               
    50   not found                               
    52   not found                               
    53   not found                               
    54   not found                               
    55   not found                               
    56   not found                               
    57   not found                               
    58   not found                               
    60   not found                               
    61   not found                               
    62   not found                               
    63   not found                               
    64   not found                               
    65   not found                               
    66   not found                               

Saving /home/zong/Desktop/1/095649bb_Mde_hybrid_conservative/miniasm_assembly/15_contigs_placed.gfa

Was this normal?

Thanks much,

Yu

**Comment by rrwick** [comment]
Hi Yu,

Unicycler was very much broken with newer versions of Racon! The Racon polishing was effectively not happening at all, so Unicycler was relying on its other means of bridging.

I think this is fixed in the [latest version (v0.4.6)](https://github.com/rrwick/Unicycler/releases) so give it a try! Let me know if you're still having problems.

Ryan
