### ISSUE TITLE
Tweaking  --depth_filter

### ISSUE THREAD

**Issue by sjackman** [rrwick/Unicycler#92]
I have a data set with some off-target reads at low depth. These off-target contigs assembly into small linear sequences, and they're causing Unicycler to pick a less-than-perfect value for *k*. I'm going to try tweaking `--depth_filter` to remove these off-target sequences. I've run Unicycler with the default value of `--depth_filter=0.25` and also `--keep 3`. Can I rerun Unicycler with a different value of `--depth_filter`, and can it resume without having to rerun the SPAdes assemblies? Any other tips for dealing with low-depth off-target sequence?

**Comment by sjackman** [comment]
```
K-mer   Contigs   Dead ends   Score   
   25    19,017          83   6.19e-07
   45     6,181          53   2.94e-06 ← best
   59     4,365          98   2.29e-06
   73     3,581         210   1.32e-06
   85     3,117         451   7.08e-07
   93     3,968         787   3.19e-07
  101     3,437       1,017   2.86e-07
  109     2,872       1,202   2.89e-07
  115     2,827       1,471   2.40e-07
  121     2,348       1,742   2.44e-07
```

**Comment by sjackman** [comment]
Even for the largest value of *k*=121, the genome that I want to assemble is in a single component. A possible hack would be to calculate `Score` only for the largest component of the graph. I'm thinking that I could use `bandage reduce` and `bandage info` to calculate the Unicycler score for each SPAdes assembly, and then specify that particular value of *k* to Unicycler.

I'm thinking I can use `bandage reduce --scope aroundnodes --nodes 1  --distance 999999` to extract the largest component, `bandage info` to calculate the `Contigs` and `Dead ends`, and then calculate the score of the largest component with R.

Any thoughts on this approach?

**Comment by sjackman** [comment]
Here's the graph for *k*=121.

![graph](https://user-images.githubusercontent.com/291551/37117910-656e9aec-2207-11e8-81c7-341abd12186b.png)

**Comment by sjackman** [comment]
```
  --depth_filter DEPTH_FILTER         Filter out contigs lower than this fraction of the chromosomal depth, if
                                      doing so does not result in graph dead ends (default: 0.25)
```
Since the depth filter does take into account the topology of the graph to avoid creating dead ends, is it reasonable to try `--depth_filter=1`?

**Comment by sjackman** [comment]
Computing the score of the largest connected component was fruitful.

k-mer | Contigs | Dead ends  | Inverse score | Score
-----:|--------:|-----------:|--------------:|----------
   25 | 17409   | 53         | 50764644      |  0.000000
   45 | 4228    | 20         | 1864548       |  0.000001
   59 | 2583    | 19         | 1033200       |  0.000001
   73 | 1867    | 21         | 903628        |  0.000001
   85 | 1451    | 20         | 639891        |  0.000002 ← best
   93 | 1917    | 66         | 8605413       |  0.000000
  101 | 1466    | 52         | 4117994       |  0.000000
  109 | 1076    | 41         | 1898064       |  0.000001
  115 | 964     | 56         | 3132036       |  0.000000
  121 | 523     | 62         | 2075787       |  0.000000

I'll try `--kmer_count=1 --min_kmer_frac=0.68 --max_kmer_frac=0.68` to specify *k*=85. A `--kmer` option would be useful to specify a particular value of *k*.

**Comment by sjackman** [comment]
Well that caused a division by zero error, so I'll try…
```
--kmer_count=2 --min_kmer_frac=0.68 --max_kmer_frac=0.69
```

**Comment by rrwick** [comment]
Hi Shaun,

Unicycler does have a `--kmers` option now (can't remember exactly when that was added), so that makes your last stuff a bit easier.

Unicycler's depth filter could be completely thrown off if the contamination was actually longer than the correct genome. E.g. when the main genome was 4 Mbp but the contaminant was 5 Mbp. This made Unicycler settle on the wrong depth for the main genome's chromosome. I think I fixed this in v0.4.5 (4123cd7, now it only uses the longest contigs to determine the chromosomal depth). Along with a few other tweaks, I hope the current version of Unicycler handles this read set better.

As a last resort hack, what I've done in a few cases is to manually edit the first graph it saves (001_best_spades_graph.gfa) and then rerun Unicycler. E.g. use some awk or something to filter things out from the GFA. When Unicycler sees that file in its assembly directory, it will use it instead of running SPAdes. Manually editing the GFA isn't an elegant solution, but it is flexible and has gotten me out a few binds!

Ryan

**Comment by sjackman** [comment]
I posted this issue on 2018-Mar-7, so I was likely using Unicycler 0.4.4. I'll try the automatic *k*-mer size selection again, and see which it picks this time.

The `--kmers` option is quiet useful! Thanks!

I didn't know that it was possible to resume a Unicycler assembly from a particular stage. Excellent! Does that work for all stages? Is there a command line option to specify running a particular stage (or stages)? Is there a command line option to specify resuming from a particular stage? Is there a command line option to specify stopping at a particular stage?

Does Unicycler use a particular workflow management tool under the hood? (like Snakemake)

**Comment by sjackman** [comment]
Thanks for the information, Ryan!
