### ISSUE TITLE
Bioconda installs the old version

### ISSUE THREAD

**Issue by apredeus** [rrwick/Unicycler#95]
Hello, 

I've install unicycler using bioconda in a virtual environment with python 3.6, and it defaults to 0.3.0b with no option to upgrade it. Probably the recipe need to be updated? If you could suggest the way to install 0.4.4 from bioconda I'd be very grateful.

**Comment by apredeus** [comment]
Also, is there no wrapper in the latest release? I've done the python3 setup on the cloned repository, but no "unicycler" binary was generated - just several python scripts, e.g. unicycler-runner.py. Just wanted to make sure I was using the right thing.

**Comment by sjackman** [comment]
The most recent version of Unicycler is packaged by Linuxbrew/Homebrew.
See http://linuxbrew.sh or https://brew.sh for installation instructions, and then run
```
brew install brewsci/bio/unicycler
```

**Comment by apredeus** [comment]
Thank you for your suggestion. It's the first time I'm using linuxbrew, so I might be missing something obvious, but linuxbrew install seems to fail with this message (see below). Wget also does not work for the mentioned link. 

> ==> Installing brewsci/bio/unicycler dependency: swig
> ==> Downloading https://downloads.sourceforge.net/project/swig/swig/swig-3.0.12/swig-3.0.12.tar.gz
> 
> curl: (60) SSL certificate problem: unable to get local issuer certificate
> More details here: http://curl.haxx.se/docs/sslcerts.html
> 
> curl performs SSL certificate verification by default, using a "bundle"
>  of Certificate Authority (CA) public keys (CA certs). If the default
>  bundle file isn't adequate, you can specify an alternate file
>  using the --cacert option.
> If this HTTPS server uses a certificate signed by a CA represented in
>  the bundle, the certificate verification probably failed due to a
>  problem with the certificate (it might be expired, or the name might
>  not match the domain name in the URL).
> If you'd like to turn off curl's verification of the certificate, use
>  the -k (or --insecure) option.
> Error: Failed to download resource "swig"
> Download failed: https://downloads.sourceforge.net/project/swig/swig/swig-3.0.12/swig-3.0.12.tar.gz

**Comment by apredeus** [comment]
And I've tried [these suggestions](https://github.com/Linuxbrew/brew/wiki/FAQ#why-does-curl-fail), but that didn't help.

**Comment by apredeus** [comment]
Thank you for the answer! I don't think it's on our end - If i simply try to run 

> curl -k https://downloads.sourceforge.net/project/swig/swig/swig-3.0.12/swig-3.0.12.tar.gz

it doesn't work as well. The only thing that works is to remove the https (use http) + wget.

I've also tried reinstalling openssl and curl as was mentioned in the link above, but that didn't help.

**Comment by sjackman** [comment]
In that case, try the following work around…
```sh
curl -o $(brew --cache -s swig) http://downloads.sourceforge.net/project/swig/swig/swig-3.0.12/swig-3.0.12.tar.gz
brew install swig
```

Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `swig`.
Another possible workaround for you is `brew install --force-bottle swig `, but no promises.

**Comment by apredeus** [comment]
Thanks again. The workaround didn't work since it seems to be downloading something wrong (I think there's a redirect and curl goes wrong on that). I've downloaded it with wget to cache and it worked though. 

About installing in `/home/linuxbrew` - unfortunately I do all the work on a server where I don't have any root privileges. Thus, no `/home` for me! 

Thanks again for the help, I appreciate it.

**Comment by apredeus** [comment]
Ok, I got ahead of myself.. Something wrong happened with python@2, and it could not find setuptools. After I've ran 

```
brew link --overwrite python@2
brew postinstall python@2
```
I still got the following error: 

> ==> Postinstalling python@2
> ==> /pub37/alexp/.linuxbrew/Cellar/python@2/2.7.14_4/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-script
> Last 15 lines from /pub37/alexp/.cache/Homebrew/Logs/python@2/post_install.01.python:
> --install-scripts=/pub37/alexp/.linuxbrew/Cellar/python@2/2.7.14_4/bin
> --install-lib=/pub37/alexp/.linuxbrew/lib/python2.7/site-packages
> 
> Traceback (most recent call last):
>   File "setup.py", line 11, in <module>
>     import setuptools
>   File "/pub37/alexp/.linuxbrew/Cellar/python@2/2.7.14_4/libexec/setuptools/setuptools/__init__.py", line 14, in <module>
>     from setuptools.dist import Distribution, Feature
>   File "/pub37/alexp/.linuxbrew/Cellar/python@2/2.7.14_4/libexec/setuptools/setuptools/dist.py", line 23, in <module>
>     from setuptools import windows_support
>   File "/pub37/alexp/.linuxbrew/Cellar/python@2/2.7.14_4/libexec/setuptools/setuptools/windows_support.py", line 2, in <module>
>     import ctypes
>   File "/pub37/alexp/.linuxbrew/Cellar/python@2/2.7.14_4/lib/python2.7/ctypes/__init__.py", line 7, in <module>
>     from _ctypes import Union, Structure, Array
> ImportError: No module named _ctypes

I think it's because Python overlaps with system-wide installation. Is there a good way to install linuxbrew in a virtual environment? 

Otherwise, I really would appreciate an update to bioconda recipe. It's a lot easier to organize the insane number of programs used in bioinformatics using the virtual environments..

**Comment by sjackman** [comment]
> The workaround didn't work since it seems to be downloading something wrong

Should have been `curl -L`. Fixed above https://github.com/rrwick/Unicycler/issues/95#issuecomment-383585054

**Comment by sjackman** [comment]
I haven't run into that issue installing `python@2` myself. Open an issue at https://github.com/Linuxbrew/homebrew-core/issues and report the output of `brew gist-logs python@2`

> I think it's because Python overlaps with system-wide installation. Is there a good way to install linuxbrew in a virtual environment?

Linuxbrew is installed in its own environment in `~/.linuxbrew` that is isolated from your host environment.

**Comment by rien333** [comment]
@apredeus  did you ever fix this?

**Comment by apredeus** [comment]
@rien333 no - it kept finding some new problems, so I decided not to do it this way. Since conda only installs a very old version of unicycler, I've ended up installing all the dependencies in conda, and then just cloning the repo. 

> conda create -n unicycler 
> source activate unicycler
> conda install -c python=3.6 anaconda
> conda install unicycler
> conda install racon=0.5.0 
> conda remove unicycler
> git clone https://github.com/rrwick/Unicycler.git
> cd Unicycler
> python3 setup.py install --user

Also had to change pilon script settings to allow it to use up to 20gb: 

> vi ~/miniconda2/envs/unicycler/bin/pilon 
> ##find the following line:  
> default_jvm_mem_opts = ['-Xmx512m','-Xmg1g'] 
> ##change to 
> default_jvm_mem_opts = ['-Xmx512m','-Xmg20g']

@rrwick I know at least three people who do not use Unicycler because it was a pain to install. Which is a shame because I think it's a great tool.

**Comment by rien333** [comment]
@apredeus oops, i was specifically referrig to your particulair python@2 postinstall issue, which im also experiencing.

**Comment by sjackman** [comment]
@rien333 You can if you like report an issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. Be sure to include the output of `brew gist-logs python@2` to aid troubleshooting.

**Comment by sjackman** [comment]
I've opened PR https://github.com/bioconda/bioconda-recipes/pull/11240 to update Bioconda to Unicycler 0.4.7.
