### ISSUE TITLE
Error: Unicycler requires SPAdes v3.6.2 or higher

### ISSUE THREAD

**Issue by Cheyou** [rrwick/Unicycler#98]
Hello,

Why the following error occurs even I use spade v3.11.1
Error: Unicycler requires SPAdes v3.6.2 or higher
--spades_path /data/spades/SPAdes-3.11.1-Linux/bin/spades.py
Thank you!

**Comment by rrwick** [comment]
I suspect this issue is already fixed (ac60f60, probably in Unicycler v0.4.1 or so). Which version of Unicycler are you using? If it's an older version, trying grabbing the latest (v0.4.6) and see if it works for you there.

Ryan
